import { z } from 'zod';
import { logger } from '../utils/logger';
import {
  ADMIN_NOTIFICATION_EMAIL,
  button,
  emailColors,
  escapeHtml,
  fromAddress,
  getTransporter,
  headerSafe,
  shell,
  webPublicUrl,
} from './email-service';

/**
 * Transactional email for CNC build packs.
 *
 * Every send here is best-effort: the order is already paid, queued or
 * generated by the time one of these runs, and a dead SMTP must not roll back
 * a payment or strand a pack. Failures are logged and swallowed, exactly as
 * the gym-claim mails do.
 *
 * The buyer gets two mails on the happy path — "we've got it, it's building"
 * and "it's ready, here it is" — and Boardsesh gets one when a pack gives up.
 */

const emailSchema = z.string().email();

export type CncLicenceTierLabel = 'personal' | 'commercial_single';

/** What the buyer bought, in words rather than an enum value. */
function tierLabel(tier: CncLicenceTierLabel): string {
  return tier === 'commercial_single' ? 'Commercial single-build licence' : 'Personal licence';
}

/** The licence id, styled so it is readable on paper and in a support reply. */
function licenceLine(licenceId: string): string {
  return `
    <p style="color: ${emailColors.textSecondary}; font-size: 14px; margin: 24px 0 4px;">Licence</p>
    <p style="color: ${emailColors.textPrimary}; font-size: 20px; font-weight: 600; letter-spacing: 1px; margin: 0;">${escapeHtml(licenceId)}</p>
  `;
}

export type SendCncOrderReceivedEmailInput = {
  to: string;
  licenseeName: string;
  licenceId: string;
  /** The wall, as the catalogue labels it — e.g. "Kilter Homewall 10x12". */
  boardLabel: string;
  tier: CncLicenceTierLabel;
  /** Where the buyer watches the build and downloads the pack. */
  orderUrl: string;
};

/**
 * "Paid, and the files are being cut."
 *
 * Sent from the Stripe webhook the moment payment lands, before the generator
 * has done anything — so it deliberately promises a second email rather than a
 * download link that does not work yet.
 */
export async function sendCncOrderReceivedEmail({
  to,
  licenseeName,
  licenceId,
  boardLabel,
  tier,
  orderUrl,
}: SendCncOrderReceivedEmailInput): Promise<void> {
  try {
    const validatedEmail = emailSchema.parse(to);
    const safeName = escapeHtml(licenseeName);
    const safeBoard = escapeHtml(boardLabel);

    await getTransporter().sendMail({
      from: fromAddress(),
      to: validatedEmail,
      subject: headerSafe(`Your build plans are being generated — ${licenceId}`),
      html: shell(
        'Your build plans are being generated',
        `
        <p style="color: ${emailColors.textPrimary}; font-size: 16px; line-height: 1.5;">
          Thanks ${safeName} — payment's through. We're cutting the sheet layouts, drill patterns and
          PDFs for your <strong>${safeBoard}</strong> now. It usually takes a couple of minutes.
        </p>
        <p style="color: ${emailColors.textPrimary}; font-size: 16px; line-height: 1.5;">
          We'll email you the moment the pack is ready to download. You can also watch it build here.
        </p>
        ${button(orderUrl, 'Check your order')}
        ${licenceLine(licenceId)}
        <p style="color: ${emailColors.textSecondary}; font-size: 14px; line-height: 1.5; margin-top: 24px;">
          ${escapeHtml(tierLabel(tier))} — one wall. It's printed on every file in the pack.
        </p>
        <hr style="border: none; border-top: 1px solid ${emailColors.border}; margin: 32px 0;" />
        <p style="color: ${emailColors.textMuted}; font-size: 12px;">
          Keep this email: the licence id above is what support and any warranty question starts from.
        </p>
      `,
      ),
      text: `Thanks ${licenseeName} — payment's through. We're generating the build plans for your ${boardLabel} now; it usually takes a couple of minutes and we'll email you when they're ready.\n\nWatch it build: ${orderUrl}\n\nLicence: ${licenceId} (${tierLabel(tier)} — one wall)`,
    });
  } catch (error) {
    logger.warn('[cnc-email] Failed to send the order-received email:', error instanceof Error ? error.message : error);
  }
}

export type SendCncPackReadyEmailInput = {
  to: string;
  licenseeName: string;
  licenceId: string;
  boardLabel: string;
  /** Where the buyer downloads. Never a raw object-store URL — the route checks ownership. */
  orderUrl: string;
};

/**
 * "It's cut, come and get it."
 *
 * Links to the order page rather than to a file: the download route checks
 * ownership and refund status on every hit, and a link in an inbox is exactly
 * the thing that gets forwarded.
 */
export async function sendCncPackReadyEmail({
  to,
  licenseeName,
  licenceId,
  boardLabel,
  orderUrl,
}: SendCncPackReadyEmailInput): Promise<void> {
  try {
    const validatedEmail = emailSchema.parse(to);
    const safeName = escapeHtml(licenseeName);
    const safeBoard = escapeHtml(boardLabel);

    await getTransporter().sendMail({
      from: fromAddress(),
      to: validatedEmail,
      subject: headerSafe(`Your build plans are ready — ${licenceId}`),
      html: shell(
        'Your build plans are ready',
        `
        <p style="color: ${emailColors.textPrimary}; font-size: 16px; line-height: 1.5;">
          ${safeName}, the pack for your <strong>${safeBoard}</strong> is cut and waiting: DXFs for every
          panel, printable PDFs, a bill of materials and the build notes.
        </p>
        ${button(orderUrl, 'Download your pack')}
        ${licenceLine(licenceId)}
        <hr style="border: none; border-top: 1px solid ${emailColors.border}; margin: 32px 0;" />
        <p style="color: ${emailColors.textMuted}; font-size: 12px;">
          The download link opens your order page and checks it's you, so it's safe to keep this email —
          but the files themselves are licensed to you for one wall. Send us a photo when it's up.
        </p>
      `,
      ),
      text: `${licenseeName}, the build plans for your ${boardLabel} are ready — DXFs for every panel, printable PDFs, a bill of materials and the build notes.\n\nDownload: ${orderUrl}\n\nLicence: ${licenceId}`,
    });
  } catch (error) {
    logger.warn('[cnc-email] Failed to send the pack-ready email:', error instanceof Error ? error.message : error);
  }
}

export type SendCncPackFailedAdminEmailInput = {
  licenceId: string;
  orderId: number;
  boardLabel: string;
  licenseeEmail: string;
  attempts: number;
  /** The generator's own error. Goes to Boardsesh only — buyers see a fixed message. */
  lastError: string | null;
};

/**
 * Tell Boardsesh a paid pack gave up.
 *
 * This is the one mail that carries generator internals, and it is why the
 * buyer's `errorMessage` can stay a fixed public string: somebody has already
 * been handed the real error, the licence id and the buyer's address, and
 * every one of these is a refund or a manual regenerate waiting to happen.
 */
export async function sendCncPackFailedAdminEmail({
  licenceId,
  orderId,
  boardLabel,
  licenseeEmail,
  attempts,
  lastError,
}: SendCncPackFailedAdminEmailInput): Promise<void> {
  try {
    const safeLicence = escapeHtml(licenceId);
    const safeBoard = escapeHtml(boardLabel);
    const safeBuyer = escapeHtml(licenseeEmail);
    const safeError = escapeHtml(lastError ?? 'no error recorded');
    const orderUrl = `${webPublicUrl()}/build-plans/orders/${encodeURIComponent(licenceId)}`;

    await getTransporter().sendMail({
      from: fromAddress(),
      to: ADMIN_NOTIFICATION_EMAIL,
      subject: headerSafe(`CNC pack generation failed: ${licenceId}`),
      html: shell(
        'A paid build pack failed to generate',
        `
        <p style="color: ${emailColors.textPrimary}; font-size: 16px; line-height: 1.5;">
          <strong>${safeLicence}</strong> (order ${String(orderId)}) gave up after ${String(attempts)} attempts.
          The buyer has paid and is waiting.
        </p>
        <p style="color: ${emailColors.textSecondary}; font-size: 15px; line-height: 1.5;">
          Wall: ${safeBoard}<br />
          Buyer: ${safeBuyer}
        </p>
        <p style="color: ${emailColors.textSecondary}; font-size: 14px; line-height: 1.5;">Last error</p>
        <pre style="color: ${emailColors.textPrimary}; font-size: 13px; background: #f5f5f4; padding: 12px; border-radius: 6px; white-space: pre-wrap; word-break: break-word;">${safeError}</pre>
        ${button(orderUrl, 'Open the order')}
      `,
      ),
      text: `${licenceId} (order ${String(orderId)}) failed after ${String(attempts)} attempts.\n\nWall: ${boardLabel}\nBuyer: ${licenseeEmail}\n\nLast error: ${lastError ?? 'no error recorded'}\n\n${orderUrl}`,
    });
  } catch (error) {
    logger.warn(
      '[cnc-email] Failed to send the pack-failed admin email:',
      error instanceof Error ? error.message : error,
    );
  }
}
