// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Boardsesh contributors

/// <reference types="node" />
/**
 * Regenerates `src/generated/woods-led-maps-data.ts` from the Woods Board LED
 * lookup tables that live alongside the protocol spec
 * (`docs/woods-board-led-maps/light-map-{8x10,12x12}.json`).
 *
 * Each table maps a hold's `baseHoldLocation` (the id the Woods data API uses in
 * a problem's `holdList`) to the physical LED index on that board size's strip.
 * The Woods board has no Aurora-style catalog in the database, so — like the
 * MoonBoard serpentine — this data is committed as a TS module rather than
 * queried from Postgres by `generate-board-constants.ts`.
 *
 * Run from the repo root:
 *   node --import tsx packages/board-constants/scripts/generate-woods-led-maps.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..', '..', '..');
const docsDir = join(repoRoot, 'docs', 'woods-board-led-maps');
const outFile = join(here, '..', 'src', 'generated', 'woods-led-maps-data.ts');

const SIZES = [
  { size: '8x10', file: 'light-map-8x10.json' },
  { size: '12x12', file: 'light-map-12x12.json' },
] as const;

function loadTable(file: string): Record<number, number> {
  const raw = JSON.parse(readFileSync(join(docsDir, file), 'utf8')) as Record<string, number>;
  const table: Record<number, number> = {};
  for (const [key, ledIndex] of Object.entries(raw)) {
    const baseHoldLocation = Number(key);
    if (!Number.isInteger(baseHoldLocation) || !Number.isInteger(ledIndex)) {
      throw new Error(`Non-integer entry in ${file}: ${key} -> ${ledIndex}`);
    }
    table[baseHoldLocation] = ledIndex;
  }
  return table;
}

function renderTable(table: Record<number, number>): string {
  // One entry per line, matching the repo formatter's object-literal style so a
  // regenerate produces a diff-free file.
  return Object.keys(table)
    .map(Number)
    .sort((a, b) => a - b)
    .map((baseHoldLocation) => `    ${baseHoldLocation}: ${table[baseHoldLocation]},`)
    .join('\n');
}

const blocks = SIZES.map(({ size, file }) => {
  const table = loadTable(file);
  return `  '${size}': {\n${renderTable(table)}\n  },`;
}).join('\n');

const output = `/**
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY ⚠️
 *
 * Auto-generated by:
 *   node --import tsx packages/board-constants/scripts/generate-woods-led-maps.ts
 *
 * Source of truth: docs/woods-board-led-maps/light-map-{8x10,12x12}.json
 * (see docs/WOODS_BLUETOOTH_PROTOCOL_SPEC.md §7). Maps a hold's
 * \`baseHoldLocation\` to its physical LED index, per board size. A lookup that
 * returns no entry means that position has no LED on that board size and is
 * skipped when building a BLE command.
 */

export type WoodsBoardSize = '8x10' | '12x12';

export const WOODS_LED_MAPS: Record<WoodsBoardSize, Record<number, number>> = {
${blocks}
};
`;

writeFileSync(outFile, output);
console.log(`Wrote ${outFile}`);
