/// <reference types="node" />
/**
 * Pure loader/renderers for the Woods Board LED lookup tables
 * (`docs/woods-board-led-maps/light-map-{8x10,12x12}.json`), shared by the
 * generator entry (`generate-woods-led-maps.ts`) and the drift test that pins
 * both committed artifacts to the JSON source (`woods-led-maps-drift.test.ts`).
 *
 * Two artifacts render from the same tables:
 *   - `src/generated/woods-led-maps-data.ts` — the JS encoder's maps
 *     (`@boardsesh/ble-protocol/woods`)
 *   - `packages/mobile/modules/live-activity/ios/WoodsBoardData.swift` — the
 *     native Swift encoder's maps (#3314), in the embedded-JSON style of
 *     `BoardPlacementData.swift`
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

export const WOODS_LED_MAP_SIZES = [
  { size: '8x10', file: 'light-map-8x10.json' },
  { size: '12x12', file: 'light-map-12x12.json' },
] as const;

export type WoodsLedMapSize = (typeof WOODS_LED_MAP_SIZES)[number]['size'];

export type WoodsLedTables = Record<WoodsLedMapSize, Record<number, number>>;

export function loadWoodsLedTables(docsDir: string): WoodsLedTables {
  const tables = {} as WoodsLedTables;
  for (const { size, file } of WOODS_LED_MAP_SIZES) {
    const raw = JSON.parse(readFileSync(join(docsDir, file), 'utf8')) as Record<string, number>;
    const table: Record<number, number> = {};
    for (const [key, ledIndex] of Object.entries(raw)) {
      const baseHoldLocation = Number(key);
      if (!Number.isInteger(baseHoldLocation) || !Number.isInteger(ledIndex)) {
        throw new Error(`Non-integer entry in ${file}: ${key} -> ${ledIndex}`);
      }
      table[baseHoldLocation] = ledIndex;
    }
    tables[size] = table;
  }
  return tables;
}

function sortedBaseHoldLocations(table: Record<number, number>): number[] {
  return Object.keys(table)
    .map(Number)
    .sort((a, b) => a - b);
}

export function renderWoodsLedMapsTs(tables: WoodsLedTables): string {
  const blocks = WOODS_LED_MAP_SIZES.map(({ size }) => {
    // One entry per line, matching the repo formatter's object-literal style so
    // a regenerate produces a diff-free file.
    const rows = sortedBaseHoldLocations(tables[size])
      .map((baseHoldLocation) => `    ${baseHoldLocation}: ${tables[size][baseHoldLocation]},`)
      .join('\n');
    return `  '${size}': {\n${rows}\n  },`;
  }).join('\n');

  return `/**
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY ⚠️
 *
 * Auto-generated by:
 *   node --import tsx packages/board-constants/scripts/generate-woods-led-maps.ts
 *
 * Source of truth: docs/woods-board-led-maps/light-map-{8x10,12x12}.json
 * (see docs/WOODS_BLUETOOTH_PROTOCOL_SPEC.md §7). Maps a hold's
 * \`baseHoldLocation\` to its physical LED index, per board size. A lookup that
 * returns no entry means that position has no LED on that board size and is
 * skipped when building a BLE command.
 */

export type WoodsBoardSize = '8x10' | '12x12';

export const WOODS_LED_MAPS: Record<WoodsBoardSize, Record<number, number>> = {
${blocks}
};
`;
}

export function renderWoodsBoardDataSwift(tables: WoodsLedTables): string {
  // One-line JSON literal decoded at runtime, like BoardPlacementData.swift —
  // a 1,379-entry Swift dictionary literal would blow up the type-checker.
  const json = `{${WOODS_LED_MAP_SIZES.map(
    ({ size }) =>
      `"${size}":{${sortedBaseHoldLocations(tables[size])
        .map((baseHoldLocation) => `"${baseHoldLocation}":${tables[size][baseHoldLocation]}`)
        .join(',')}}`,
  ).join(',')}}`;

  return `// DO NOT EDIT THIS FILE MANUALLY
//
// This file is auto-generated by running:
//   node --import tsx packages/board-constants/scripts/generate-woods-led-maps.ts
//
// Woods Board LED lookup tables for the native iOS BLE layer (#3314).
// Source of truth: docs/woods-board-led-maps/light-map-{8x10,12x12}.json
// (docs/WOODS_BLUETOOTH_PROTOCOL_SPEC.md §7). Maps a hold's baseHoldLocation
// to its physical LED index, per board size. A missing key means that position
// has no LED on that board size and is skipped when encoding.

import Foundation

enum WoodsBoardData {
    private static let ledMapsJSON = """
${json}
"""

    private static let ledMaps: [String: [Int: Int]] = decode(ledMapsJSON)

    /// Woods size_id → dimension per WOODS_SIZES in
    /// packages/shared/board-config/src/woods-config.ts. Unknown sizes return
    /// nil so the caller can refuse the write instead of darkening the wall.
    static func ledMap(forSizeId sizeId: Int) -> [Int: Int]? {
        switch sizeId {
        case 1: return ledMaps["8x10"]
        case 2: return ledMaps["12x12"]
        default: return nil
        }
    }

    private static func decode(_ json: String) -> [String: [Int: Int]] {
        guard let data = json.data(using: .utf8),
              let decoded = try? JSONDecoder().decode([String: [String: Int]].self, from: data)
        else {
            // Unreachable for a committed artifact (the drift test pins the
            // literal to the docs JSON) — but a decode failure must be loud in
            // development, not just a downstream "No Woods LED table" log.
            assertionFailure("WoodsBoardData.ledMapsJSON failed to decode — regenerate via generate-woods-led-maps.ts")
            return [:]
        }
        return decoded.mapValues { table in
            table.reduce(into: [:]) { result, entry in
                if let baseHoldLocation = Int(entry.key) {
                    result[baseHoldLocation] = entry.value
                }
            }
        }
    }
}
`;
}
