import type { AppSettings } from './types';

export const DEFAULT_SETTINGS: AppSettings = {
  defaultBoardUuid: null,
  syncEnabledBoards: [],
  offlineBoardsV1: [],
  offlineDownloadTriggers: {},
  offlineDownloadAllTapPending: false,
  autoOfflineBoards: false,
  offlineMode: false,
  autoConnectBle: true,
  autoDisconnectBle: false,
  autoDisconnectTimeoutSeconds: 30,
  moonboardLightAdjacentHolds: false,
  lightOnSwipe: true,
  lightOnClimbTap: true,
  keepScreenAwake: true,
  restTimerTargetSeconds: null,
  restTimerAutoAdvance: false,
  restTimerMode: 'afterTick',
  theme: 'system',
  hapticFeedbackEnabled: true,
  notifySessionInvites: true,
  notifyClimbComments: true,
  kioskHintSeen: false,
  browseNoticeSeen: false,
  bottomChromeDiagnostics: false,
  qaBriefSeenKey: null,
  qaVerdictSubmittedKey: null,
};
