import { describe, expect, it } from 'vitest';
import { getStaticAsset, STATIC_ASSET_MANIFEST } from '@boardsesh/static-assets';
import { MOONBOARD_LAYOUTS, MOONBOARD_SETS, getMoonBoardGeometryByFolder } from '../moonboard-config';
import { resolveStaticAssetUrl } from '../static-asset-url';

describe('resolveStaticAssetUrl', () => {
  it('keeps logical paths local when no production asset origin is configured', () => {
    expect(resolveStaticAssetUrl('brand/boardsesh-mark.png', '')).toBe('/brand/boardsesh-mark.png');
  });

  it('resolves catalog entries to immutable CDN keys', () => {
    const logicalPath = '/brand/boardsesh-mark.png';
    expect(resolveStaticAssetUrl(logicalPath, 'https://assets.boardsesh.com/')).toBe(
      `https://assets.boardsesh.com/${STATIC_ASSET_MANIFEST[logicalPath]?.objectKey}`,
    );
  });

  it('fails closed when a production build references an uncatalogued image', () => {
    expect(() => resolveStaticAssetUrl('/images/missing.webp', 'https://assets.boardsesh.com')).toThrow(
      'Static asset is missing from the generated catalog: /images/missing.webp',
    );
  });

  it('catalogs every MoonBoard image path generated by the renderer', () => {
    const generatedPaths = new Set<string>();
    for (const [layoutKey, layout] of Object.entries(MOONBOARD_LAYOUTS)) {
      const backgroundImage = getMoonBoardGeometryByFolder(layout.folder).backgroundImage.replace(/\.png$/, '.webp');
      generatedPaths.add(`/images/moonboard/${backgroundImage}`);
      generatedPaths.add(`/images/moonboard/thumbs/${backgroundImage}`);

      for (const holdSet of MOONBOARD_SETS[layoutKey as keyof typeof MOONBOARD_LAYOUTS]) {
        const imageFile = holdSet.imageFile.replace(/\.png$/, '.webp');
        generatedPaths.add(`/images/moonboard/${layout.folder}/${imageFile}`);
        generatedPaths.add(`/images/moonboard/${layout.folder}/thumbs/${imageFile}`);
      }
    }

    expect([...generatedPaths].filter((logicalPath) => !getStaticAsset(logicalPath))).toEqual([]);
  });
});
