import { describe, expect, it } from 'vitest';
import { extractSection, isJunkLine, linesOutsideFences, stripHtmlComments } from '../sections';

const HEADING = /^#{2,3}\s+test plan\s*$/i;

describe('extractSection', () => {
  it('returns the lines between the heading and the next heading', () => {
    const body = [
      '## Summary',
      'stuff',
      '## Test plan',
      '1. Open the app',
      '2. Tap Boards',
      '## Risk',
      'Risk: 1/5',
    ].join('\n');
    expect(extractSection(body, HEADING)).toEqual(['1. Open the app', '2. Tap Boards']);
  });

  it('returns null when the heading is absent, and an empty array for an empty section', () => {
    expect(extractSection('## Summary\nonly this', HEADING)).toBeNull();
    expect(extractSection(null, HEADING)).toBeNull();
    expect(extractSection('## Test plan\n## Risk', HEADING)).toEqual([]);
  });

  it('ignores headings inside a code fence and keeps the fence lines', () => {
    const body = ['## Test plan', '```', '# not a heading', '```', '1. step', '## Risk'].join('\n');
    expect(extractSection(body, HEADING)).toEqual(['```', '# not a heading', '```', '1. step']);
  });

  it('skips a heading quoted inside a code fence and finds the real one', () => {
    const body = [
      '## Summary',
      '```md',
      '## Test plan',
      '1. example only',
      '```',
      '## Test plan',
      '1. real step',
      '## Risk',
    ].join('\n');
    expect(extractSection(body, HEADING)).toEqual(['1. real step']);
    expect(extractSection('## Summary\n```\n## Test plan\n1. fenced\n```', HEADING)).toBeNull();
  });

  it('stops at a horizontal rule or a bot footer', () => {
    expect(extractSection('## Test plan\n1. step\n---\ntrailing', HEADING)).toEqual(['1. step']);
    expect(extractSection('## Test plan\n1. step\n🤖 Generated with Claude Code', HEADING)).toEqual(['1. step']);
    expect(extractSection('## Test plan\n1. step\n_Generated by [Claude](x)_', HEADING)).toEqual(['1. step']);
  });

  it('strips HTML comments before looking for the heading', () => {
    const body = '<!-- ## Test plan\n1. fake -->\n## Test plan\n1. real';
    expect(extractSection(body, HEADING)).toEqual(['1. real']);
  });

  it('handles CRLF line endings', () => {
    expect(extractSection('## Test plan\r\n1. step\r\n## Risk\r\n', HEADING)).toEqual(['1. step']);
  });
});

describe('stripHtmlComments', () => {
  it('removes multi-line comments', () => {
    expect(stripHtmlComments('a<!-- x\ny -->b')).toBe('ab');
  });
});

describe('isJunkLine', () => {
  it('drops git trailers and link-only lines but keeps prose', () => {
    expect(isJunkLine('Co-Authored-By: Someone <x@y.z>')).toBe(true);
    expect(isJunkLine('https://claude.ai/code/session_123')).toBe(true);
    expect(isJunkLine('Faster search: results in half the time')).toBe(false);
    expect(isJunkLine('See https://example.com for the flow')).toBe(false);
  });
});

describe('linesOutsideFences', () => {
  it('drops fenced blocks and their delimiters, keeping the rest in order', () => {
    expect(linesOutsideFences('a\n```\nb\n```\nc<!-- x -->')).toEqual(['a', 'c']);
  });
});
