/// <reference types="node" />

/**
 * Pure Conventional Commit parsing + validation, no I/O. Hand-rolled (no
 * @commitlint/* dep) to match this repo's minimal-dependency convention and so
 * the type→changelog-category map can be shared with changelog-transform.ts.
 *
 * Kept free of I/O so it's unit-testable without touching git (see
 * scripts/__tests__/commit-message-transform.test.ts). The thin I/O wrapper that
 * reads commit messages / git ranges lives in scripts/check-commit-message.ts.
 */

// Conventional Commit types we accept. feat/fix/perf/refactor carry user-facing
// weight (changelog categorisation); the rest are housekeeping but still must be
// well-formed so history stays machine-readable.
export const ALLOWED_TYPES = [
  'feat',
  'fix',
  'perf',
  'refactor',
  'docs',
  'test',
  'build',
  'ci',
  'chore',
  'style',
  'revert',
] as const;

export type ConventionalType = (typeof ALLOWED_TYPES)[number];

// Optional scope allowlist seeded from observed `git log` scopes. Unscoped
// commits are allowed; a scope outside this set is rejected so typos
// (`mobil`, `web-app`) don't fragment the history. Add real new scopes here.
export const ALLOWED_SCOPES = [
  'mobile',
  'mobile-ota',
  'mobile-screenshots',
  'ios',
  'android',
  'web',
  'backend',
  'shared',
  'db',
  'deps',
  'ci',
  'repo',
  'sync',
  'app-store',
  'asc',
  'store',
  'screenshot',
  'fastlane',
  'board-presence',
] as const;

// The longest subject we accept. Conventional-changelog's default is 100; keep
// it so a wrapped one-liner stays readable in `git log --oneline`.
export const MAX_SUBJECT_LENGTH = 100;

export type ParsedConventional = {
  type: string;
  scope: string | null;
  breaking: boolean;
  description: string;
};

// `type(scope)!: description` — scope and the breaking `!` are optional. Capture
// groups: 1=type, 2=scope (without parens), 3=breaking marker, 4=description.
const CONVENTIONAL_PATTERN = /^([a-z]+)(?:\(([^)]+)\))?(!)?:[ ](.+)$/;

/**
 * Parses a single commit subject (the first line) into its Conventional Commit
 * parts. Returns null when the subject doesn't match the `type: description`
 * shape at all (callers decide whether that's an error or a skip).
 */
export function parseConventional(subject: string): ParsedConventional | null {
  const match = CONVENTIONAL_PATTERN.exec(subject.trim());
  if (!match) return null;
  const [, type, scope, breaking, description] = match;
  return {
    type,
    scope: scope ?? null,
    breaking: breaking === '!',
    description,
  };
}

/**
 * True for subjects we deliberately don't lint: git's own merge/revert commits
 * and rebase autosquash fixup/squash markers. These are generated by tooling and
 * never authored by hand, so holding them to the Conventional format is noise.
 */
export function isSkippedSubject(subject: string): boolean {
  const trimmed = subject.trim();
  return trimmed.startsWith('Merge ') || trimmed.startsWith('Revert ') || /^(fixup|squash)! /.test(trimmed);
}

export type CommitValidation = { ok: boolean; errors: string[] };

/**
 * Validates a commit subject against the Conventional Commit rules. Skipped
 * subjects (merge/revert/autosquash) are reported as valid with no errors.
 */
export function validateCommitSubject(subject: string): CommitValidation {
  const trimmed = subject.trim();

  if (!trimmed) {
    return { ok: false, errors: ['Commit subject is empty.'] };
  }
  if (isSkippedSubject(trimmed)) {
    return { ok: true, errors: [] };
  }

  const errors: string[] = [];

  if (trimmed.length > MAX_SUBJECT_LENGTH) {
    errors.push(`Subject is ${trimmed.length} chars; keep it under ${MAX_SUBJECT_LENGTH}.`);
  }

  const parsed = parseConventional(trimmed);
  if (!parsed) {
    errors.push(
      `Not a Conventional Commit. Use "type(scope): description", e.g. "fix(mobile): stop the queue drifting". Allowed types: ${ALLOWED_TYPES.join(', ')}.`,
    );
    return { ok: false, errors };
  }

  if (!(ALLOWED_TYPES as readonly string[]).includes(parsed.type)) {
    errors.push(`Unknown type "${parsed.type}". Allowed types: ${ALLOWED_TYPES.join(', ')}.`);
  }

  if (parsed.scope !== null && !(ALLOWED_SCOPES as readonly string[]).includes(parsed.scope)) {
    errors.push(`Unknown scope "${parsed.scope}". Allowed scopes: ${ALLOWED_SCOPES.join(', ')} (or no scope).`);
  }

  if (!parsed.description.trim()) {
    errors.push('Missing a description after the colon.');
  }

  return { ok: errors.length === 0, errors };
}
