import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createDevObjectPublisher } from './dev-object-store';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
export const DESIGN_ROOT = resolve(REPO_ROOT, 'docs/design');
const MANIFEST_PATH = resolve(DESIGN_ROOT, 'previews.json');

export const DESIGN_PREVIEW_VIEWPORTS = [
  { width: 1440, height: 900, suffix: '1440' },
  { width: 390, height: 844, suffix: '390' },
] as const;

interface DesignPreview {
  url: string;
  sha256: string;
  bytes: number;
}

export function designPreviewPath(filename: string): string {
  const path = relative(DESIGN_ROOT, resolve(filename));
  if (!path || path.startsWith(`..${sep}`) || path === '..' || !path.endsWith('.png')) {
    throw new Error(`Only PNG previews under docs/design can be published: ${filename}`);
  }
  return path.split(sep).join('/');
}

export function designPreviewFiles(htmlFiles: readonly string[]): string[] {
  const previews = htmlFiles.flatMap((filename) =>
    DESIGN_PREVIEW_VIEWPORTS.map((viewport) => filename.replace(/\.html$/, `-${viewport.suffix}.png`)),
  );
  for (const preview of previews) designPreviewPath(preview);
  return previews;
}

function readPreviews(): Record<string, DesignPreview> {
  if (!existsSync(MANIFEST_PATH)) return {};
  const parsed: unknown = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8'));
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed))
    throw new Error('Invalid design preview manifest');
  const previews: Record<string, DesignPreview> = {};
  for (const [path, entry] of Object.entries(parsed)) {
    if (
      !entry ||
      typeof entry !== 'object' ||
      !('url' in entry) ||
      typeof entry.url !== 'string' ||
      !('sha256' in entry) ||
      typeof entry.sha256 !== 'string' ||
      !('bytes' in entry) ||
      typeof entry.bytes !== 'number'
    ) {
      throw new Error(`Invalid design preview entry: ${path}`);
    }
    previews[path] = { url: entry.url, sha256: entry.sha256, bytes: entry.bytes };
  }
  return previews;
}

/** Dev-only credentials: never fall back to production media storage. */
export function createDesignPreviewPublisher(): {
  publish: (filename: string) => Promise<string>;
  finish: (completeSet?: readonly string[]) => void;
} {
  const publish = createDevObjectPublisher();
  const previews = readPreviews();

  const publishPreview = async (filename: string): Promise<string> => {
    const path = designPreviewPath(filename);
    const bytes = readFileSync(filename);
    if (!bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))) {
      throw new Error(`Not a PNG preview: ${filename}`);
    }
    const sha256 = createHash('sha256').update(bytes).digest('hex');
    const key = `design/${path.slice(0, -4)}/${sha256}.png`;
    const url = await publish(key, bytes, 'image/png');

    previews[path] = { url, sha256, bytes: bytes.length };
    return url;
  };

  // Commit links only after the caller successfully publishes the whole batch.
  // A full capture supplies its exact output set; a subset retains other links.
  const finish = (completeSet?: readonly string[]): void => {
    const keep = completeSet ? new Set(completeSet.map(designPreviewPath)) : null;
    const sorted = Object.fromEntries(
      Object.entries(previews)
        .filter(([path]) => !keep || keep.has(path))
        .sort(([left], [right]) => left.localeCompare(right)),
    );
    writeFileSync(MANIFEST_PATH, `${JSON.stringify(sorted, null, 2)}\n`);
    const links = Object.entries(sorted).map(([name, preview]) => `| ${name} | [Open preview](${preview.url}) |`);
    writeFileSync(
      resolve(DESIGN_ROOT, 'previews.md'),
      `# Design previews\n\nGenerated by \`vp run design:publish\`. PNGs live in the dev bucket.\n\n| Capture | Preview |\n| --- | --- |\n${links.join('\n')}\n`,
    );
  };
  return { publish: publishPreview, finish };
}
