import { PutObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve, sep } from 'node:path';
import { loadEnvFile } from 'node:process';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
export const DESIGN_ROOT = resolve(REPO_ROOT, 'docs/design');
const MANIFEST_PATH = resolve(DESIGN_ROOT, 'previews.json');

interface DesignPreview {
  url: string;
  sha256: string;
  bytes: number;
}

function requiredEnvironment(name: string): string {
  const configured = process.env[name]?.trim();
  if (!configured) throw new Error(`Missing ${name}; see docs/design/README.md`);
  return configured;
}

export function designPreviewPath(filename: string): string {
  const path = relative(DESIGN_ROOT, resolve(filename));
  if (!path || path.startsWith(`..${sep}`) || path === '..' || !path.endsWith('.png')) {
    throw new Error(`Only PNG previews under docs/design can be published: ${filename}`);
  }
  return path.split(sep).join('/');
}

function readPreviews(): Record<string, DesignPreview> {
  if (!existsSync(MANIFEST_PATH)) return {};
  const parsed: unknown = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8'));
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed))
    throw new Error('Invalid design preview manifest');
  const previews: Record<string, DesignPreview> = {};
  for (const [path, entry] of Object.entries(parsed)) {
    if (
      !entry ||
      typeof entry !== 'object' ||
      !('url' in entry) ||
      typeof entry.url !== 'string' ||
      !('sha256' in entry) ||
      typeof entry.sha256 !== 'string' ||
      !('bytes' in entry) ||
      typeof entry.bytes !== 'number'
    ) {
      throw new Error(`Invalid design preview entry: ${path}`);
    }
    previews[path] = { url: entry.url, sha256: entry.sha256, bytes: entry.bytes };
  }
  return previews;
}

/** Dev-only credentials: never fall back to production media storage. */
export function createDesignPreviewPublisher(): (filename: string) => Promise<string> {
  const environment = resolve(REPO_ROOT, '.env.local');
  if (existsSync(environment)) loadEnvFile(environment);
  const bucket = requiredEnvironment('DEV_S3_BUCKET_NAME');
  const endpoint = requiredEnvironment('DEV_AWS_ENDPOINT_URL');
  const publicBase = requiredEnvironment('DEV_PUBLIC_BASE_URL').replace(/\/$/, '');
  if (new URL(endpoint).protocol !== 'https:' || new URL(publicBase).protocol !== 'https:') {
    throw new Error('Dev artifact endpoint and public URL must use HTTPS');
  }
  const client = new S3Client({
    endpoint,
    region: process.env.DEV_AWS_REGION || 'auto',
    forcePathStyle: true,
    credentials: {
      accessKeyId: requiredEnvironment('DEV_AWS_ACCESS_KEY_ID'),
      secretAccessKey: requiredEnvironment('DEV_AWS_SECRET_ACCESS_KEY'),
    },
  });
  const previews = readPreviews();

  return async (filename) => {
    const path = designPreviewPath(filename);
    const bytes = readFileSync(filename);
    if (!bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))) {
      throw new Error(`Not a PNG preview: ${filename}`);
    }
    const sha256 = createHash('sha256').update(bytes).digest('hex');
    const key = `design/${path.slice(0, -4)}/${sha256}.png`;
    const url = `${publicBase}/${key.split('/').map(encodeURIComponent).join('/')}`;
    await client.send(
      new PutObjectCommand({
        Bucket: bucket,
        Key: key,
        Body: bytes,
        ContentType: 'image/png',
        CacheControl: 'public, max-age=31536000, immutable',
      }),
    );
    const response = await fetch(url, { signal: AbortSignal.timeout(30_000) });
    if (!response.ok) throw new Error(`Published preview returned HTTP ${response.status}: ${url}`);
    const uploadedHash = createHash('sha256')
      .update(Buffer.from(await response.arrayBuffer()))
      .digest('hex');
    if (uploadedHash !== sha256) throw new Error(`Published preview checksum differs: ${url}`);

    previews[path] = { url, sha256, bytes: bytes.length };
    const sorted = Object.fromEntries(Object.entries(previews).sort(([left], [right]) => left.localeCompare(right)));
    writeFileSync(MANIFEST_PATH, `${JSON.stringify(sorted, null, 2)}\n`);
    const links = Object.entries(sorted).map(([name, preview]) => `| ${name} | [Open preview](${preview.url}) |`);
    writeFileSync(
      resolve(DESIGN_ROOT, 'previews.md'),
      `# Design previews\n\nGenerated by \`vp run design:publish\`. PNGs live in the dev bucket.\n\n| Capture | Preview |\n| --- | --- |\n${links.join('\n')}\n`,
    );
    return url;
  };
}
