import { createHash } from 'node:crypto';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { extname, join, posix, relative, resolve, sep } from 'node:path';
import type {
  StaticAssetManifest,
  StaticAssetObjectKeyCatalog,
  StaticAssetRecord,
} from '../../packages/shared/static-assets/src/types';

export const STATIC_ASSET_KEY_PREFIX = 'static/v1';

const CONTENT_TYPES = Object.freeze({
  '.ico': 'image/x-icon',
  '.png': 'image/png',
  '.webp': 'image/webp',
});

const PUBLIC_RUNTIME_IMAGES = [
  'brand/boardsesh-mark.png',
  'icons/apple-touch-icon.png',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'icons/icon-maskable-512.png',
] as const;

const APP_RUNTIME_IMAGES = [
  { sourcePath: 'packages/web/app/favicon.ico', logicalPath: '/favicon.ico' },
  { sourcePath: 'packages/web/app/icon.png', logicalPath: '/icon.png' },
] as const;

export type StaticAssetSource = Readonly<{
  logicalPath: string;
  sourcePath: string;
  nativeBundle: boolean;
}>;

const toPosix = (filePath: string): string => filePath.split(sep).join(posix.sep);

function listWebpFiles(directory: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const absolutePath = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...listWebpFiles(absolutePath));
    else if (entry.isFile() && entry.name.toLowerCase().endsWith('.webp')) files.push(absolutePath);
  }
  return files;
}

export function discoverStaticAssetSources(repoRoot: string): StaticAssetSource[] {
  const publicRoot = join(repoRoot, 'packages/web/public');
  const boardRoot = join(publicRoot, 'images');
  const sources: StaticAssetSource[] = listWebpFiles(boardRoot).map((absolutePath) => {
    const publicRelativePath = toPosix(relative(publicRoot, absolutePath));
    return {
      logicalPath: `/${publicRelativePath}`,
      sourcePath: toPosix(relative(repoRoot, absolutePath)),
      nativeBundle: true,
    };
  });

  for (const publicRelativePath of PUBLIC_RUNTIME_IMAGES) {
    sources.push({
      logicalPath: `/${publicRelativePath}`,
      sourcePath: `packages/web/public/${publicRelativePath}`,
      nativeBundle: false,
    });
  }
  for (const appImage of APP_RUNTIME_IMAGES) {
    sources.push({ ...appImage, nativeBundle: false });
  }

  sources.sort((left, right) => left.logicalPath.localeCompare(right.logicalPath));
  const seenLogicalPaths = new Set<string>();
  for (const source of sources) {
    if (seenLogicalPaths.has(source.logicalPath)) throw new Error(`Duplicate static asset path: ${source.logicalPath}`);
    seenLogicalPaths.add(source.logicalPath);
    if (!existsSync(resolve(repoRoot, source.sourcePath))) {
      throw new Error(`Static asset source is missing: ${source.sourcePath}`);
    }
  }
  return sources;
}

export function createStaticAssetRecord(source: StaticAssetSource, contents: Uint8Array): StaticAssetRecord {
  const extension = extname(source.logicalPath).toLowerCase() as keyof typeof CONTENT_TYPES;
  const contentType = CONTENT_TYPES[extension];
  if (!contentType) throw new Error(`Unsupported static asset extension: ${source.logicalPath}`);
  const sha256 = createHash('sha256').update(contents).digest('hex');
  return {
    logicalPath: source.logicalPath,
    objectKey: `${STATIC_ASSET_KEY_PREFIX}/${sha256}${extension}`,
    sha256,
    bytes: contents.byteLength,
    contentType,
    nativeBundle: source.nativeBundle,
  };
}

export function buildStaticAssetManifest(repoRoot: string): StaticAssetManifest {
  const entries = discoverStaticAssetSources(repoRoot).map(
    (source) =>
      [
        source.logicalPath,
        createStaticAssetRecord(source, readFileSync(resolve(repoRoot, source.sourcePath))),
      ] as const,
  );
  return Object.fromEntries(entries);
}

function sortedManifestEntries(manifest: StaticAssetManifest): [string, StaticAssetRecord][] {
  return Object.entries(manifest).sort(([leftPath], [rightPath]) =>
    leftPath < rightPath ? -1 : leftPath > rightPath ? 1 : 0,
  );
}

export function renderStaticAssetJson(manifest: StaticAssetManifest): string {
  return `${JSON.stringify(Object.fromEntries(sortedManifestEntries(manifest)), null, 2)}\n`;
}

export function createStaticAssetObjectKeyCatalog(manifest: StaticAssetManifest): StaticAssetObjectKeyCatalog {
  return Object.fromEntries(
    sortedManifestEntries(manifest).map(([logicalPath, asset]) => [logicalPath, asset.objectKey]),
  );
}

export function renderStaticAssetObjectKeyCatalogJson(manifest: StaticAssetManifest): string {
  return `${JSON.stringify(createStaticAssetObjectKeyCatalog(manifest), null, 2)}\n`;
}

export function renderStaticAssetShellTypeScript(manifest: StaticAssetManifest): string {
  const lines = [
    '// AUTO-GENERATED by scripts/generate-static-assets.ts. Do not edit by hand.',
    "import type { StaticAssetObjectKeyCatalog } from '../types';",
    '',
    '// This deliberately excludes board art so root chrome can render without',
    '// pulling the complete board-image catalog into every browser route.',
    'export const STATIC_SHELL_ASSET_OBJECT_KEYS = {',
  ];
  for (const [logicalPath, asset] of sortedManifestEntries(manifest)) {
    if (!asset.nativeBundle) {
      lines.push(`  ${quoteTypeScriptString(logicalPath)}: ${quoteTypeScriptString(asset.objectKey)},`);
    }
  }
  lines.push('} as const satisfies StaticAssetObjectKeyCatalog;', '');
  return lines.join('\n');
}

function quoteTypeScriptString(input: string): string {
  return `'${input.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
}
