#!/bin/sh
#
# dev-db-up.sh — Start the development database stack and ensure data is ready.
#
# The pre-built Docker image (boardsesh-dev-db) already contains Kilter,
# Tension, and MoonBoard board data, a test user, and social seed data.
# This script:
#   1. Starts postgres and redis containers
#   2. Waits for postgres to be healthy
#   3. Ensures pg_hba.conf allows Docker network and Tailscale connections
#   4. Ensures the postgres user has a password set
#   5. Syncs drizzle migration tracker (public → drizzle schema)
#   6. Runs drizzle migrations (to pick up any newer migrations not yet in the image)

set -e

# PGDATA is owned by the image, not by this script: PostgreSQL 18 puts it at
# /var/lib/postgresql/18/docker, and a future major moves it again. Read it back
# out of the running container so a version bump does not silently point these
# edits at a path with no cluster in it.
postgres_data_dir() {
  docker exec "$PG_CONTAINER" sh -c 'printf %s "$PGDATA"' 2>/dev/null
}
# CDPATH is intentionally cleared only for cd.
# shellcheck disable=SC1007
REPO_ROOT=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
DRIZZLE_DIR="$REPO_ROOT/packages/db/drizzle"
GENERATED_ENV_DIR="$REPO_ROOT/.boardsesh"
GENERATED_ENV_FILE="$GENERATED_ENV_DIR/dev-db.env"

docker_daemon_available() {
  command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1
}

ensure_docker_daemon() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "ERROR: Docker CLI is not installed or not on PATH."
    echo "       Install Docker Desktop or Docker Engine and retry."
    exit 1
  fi

  if ! docker info >/dev/null 2>&1; then
    echo "ERROR: Docker daemon is not running or cannot be reached."
    echo "       Start Docker Desktop (macOS/Windows) or the Docker service and retry."
    echo "       On Linux, try 'sudo systemctl start docker' or 'dockerd'."
    exit 1
  fi
}

write_dev_db_env() {
  env_host="$1"
  env_source="$2"
  env_redis_url="$3"

  mkdir -p "$GENERATED_ENV_DIR"
  {
    printf '%s\n' '# Generated by scripts/dev-db-up.sh or scripts/dev-db-discover.ts.'
    # The backticks are literal operator guidance.
    # shellcheck disable=SC2016
    printf '%s\n' '# Do not edit by hand; rerun `vp run db:up`.'
    printf 'BOARDSESH_DEV_DB_SOURCE=%s\n' "$env_source"
    printf '%s\n' 'BOARDSESH_DEV_DB_PLAINTEXT=true'
    printf 'BOARDSESH_DEV_DB_HOST=%s\n' "$env_host"
    printf 'DATABASE_URL=postgresql://postgres:password@%s:5432/main\n' "$env_host"
    printf 'POSTGRES_URL=postgresql://postgres:password@%s:5432/main\n' "$env_host"
    printf 'POSTGRES_HOST=%s\n' "$env_host"
    printf '%s\n' 'POSTGRES_PORT=5432'
    printf '%s\n' 'POSTGRES_USER=postgres'
    printf '%s\n' 'POSTGRES_PASSWORD=password'
    printf '%s\n' 'POSTGRES_DATABASE=main'
    printf 'REDIS_URL=%s\n' "$env_redis_url"
  } > "$GENERATED_ENV_FILE"
}

detect_local_redis_url() {
  redis_container=$(docker ps --filter "publish=6379" --filter "status=running" -q 2>/dev/null | head -1)
  if [ -n "$redis_container" ]; then
    printf '%s' "redis://localhost:6379"
  fi
}

ensure_postgres_network_access() {
  echo "Ensuring pg_hba.conf allows Docker network and Tailscale connections..."
  hba_updated=false

  pgdata=$(postgres_data_dir)
  if [ -z "$pgdata" ]; then
    echo "ERROR: could not read PGDATA from the postgres container." >&2
    exit 1
  fi
  HBA_FILE="$pgdata/pg_hba.conf"

  if docker exec "$PG_CONTAINER" grep -F -q "host all all 0.0.0.0/0 md5" "$HBA_FILE" 2>/dev/null; then
    echo "  IPv4 md5 rule already present."
  else
    echo "  Adding IPv4 md5 auth rule..."
    docker exec "$PG_CONTAINER" sed -i '/host all all 0\.0\.0\.0\/0 trust/d' "$HBA_FILE" 2>/dev/null || true
    docker exec -u postgres "$PG_CONTAINER" bash -c "echo 'host all all 0.0.0.0/0 md5' >> $HBA_FILE"
    hba_updated=true
  fi

  if docker exec "$PG_CONTAINER" grep -F -q "host all all ::/0 md5" "$HBA_FILE" 2>/dev/null; then
    echo "  IPv6 md5 rule already present."
  else
    echo "  Adding IPv6 md5 auth rule..."
    docker exec "$PG_CONTAINER" sed -i '/host all all ::\/0 trust/d' "$HBA_FILE" 2>/dev/null || true
    docker exec -u postgres "$PG_CONTAINER" bash -c "echo 'host all all ::/0 md5' >> $HBA_FILE"
    hba_updated=true
  fi

  if [ "$hba_updated" = true ]; then
    docker exec -u postgres "$PG_CONTAINER" pg_ctl reload -D "$pgdata"
    echo "  pg_hba.conf updated and reloaded."
  fi
}

ensure_postgres_password() {
  echo "Ensuring postgres user password is set..."
  docker exec -u postgres "$PG_CONTAINER" psql -U postgres -d main -c \
    "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1
  echo "  Password ensured."
}

sync_drizzle_migration_tracker() {
  # Older pre-built images only have the public.__drizzle_migrations table.
  # Newer drizzle-orm uses the drizzle.__drizzle_migrations table. Ensure
  # both schemas exist and are in sync so migrations don't re-run from 0.
  echo "Syncing drizzle migration tracker..."

  docker exec -u postgres "$PG_CONTAINER" psql -U postgres -d main -q -c \
    "CREATE SCHEMA IF NOT EXISTS drizzle;"

  docker exec -u postgres "$PG_CONTAINER" psql -U postgres -d main -q -c \
    "CREATE TABLE IF NOT EXISTS drizzle.\"__drizzle_migrations\" (id SERIAL PRIMARY KEY, hash text NOT NULL, created_at bigint);"

  # Copy records from public tracker to drizzle tracker if drizzle is empty
  docker exec -u postgres "$PG_CONTAINER" psql -U postgres -d main -q -c \
    "INSERT INTO drizzle.\"__drizzle_migrations\" (hash, created_at) SELECT hash, created_at FROM public.\"__drizzle_migrations\" WHERE NOT EXISTS (SELECT 1 FROM drizzle.\"__drizzle_migrations\" LIMIT 1) AND EXISTS (SELECT 1 FROM public.\"__drizzle_migrations\" LIMIT 1) ORDER BY id;"

  DRIZZLE_COUNT=$(docker exec -u postgres "$PG_CONTAINER" psql -U postgres -d main -t -A -c \
    "SELECT count(*) FROM drizzle.\"__drizzle_migrations\";")
  echo "  drizzle.__drizzle_migrations has $DRIZZLE_COUNT records."
}

prepare_docker_postgres() {
  ensure_postgres_network_access
  ensure_postgres_password
  sync_drizzle_migration_tracker
  run_pending_drizzle_sql_migrations
  write_dev_db_env "localhost" "$1" "$(detect_local_redis_url)"
}

run_pending_drizzle_sql_migrations() {
  last_migration_created_at=$(docker exec -u postgres "$PG_CONTAINER" psql -U postgres -d main -t -A -c \
    "SELECT COALESCE((SELECT created_at FROM drizzle.\"__drizzle_migrations\" ORDER BY created_at DESC LIMIT 1), 0);")

  # This JavaScript is intentionally single-quoted.
  # shellcheck disable=SC2016
  pending_migrations=$(DRIZZLE_DIR="$DRIZZLE_DIR" LAST_MIGRATION_CREATED_AT="$last_migration_created_at" node -e '
    const fs = require("node:fs");
    const path = require("node:path");
    const crypto = require("node:crypto");

    const drizzleDir = process.env.DRIZZLE_DIR;
    const lastAppliedAt = Number(process.env.LAST_MIGRATION_CREATED_AT ?? 0);
    const journal = JSON.parse(fs.readFileSync(path.join(drizzleDir, "meta", "_journal.json"), "utf8"));

    for (const entry of journal.entries) {
      if (entry.when <= lastAppliedAt) continue;
      const sql = fs.readFileSync(path.join(drizzleDir, `${entry.tag}.sql`), "utf8");
      const hash = crypto.createHash("sha256").update(sql).digest("hex");
      process.stdout.write(`${entry.tag}|${entry.when}|${hash}\n`);
    }
  ')

  if [ -z "$pending_migrations" ]; then
    echo "  No pending migrations."
    return
  fi

  pending_count=$(printf '%s\n' "$pending_migrations" | sed '/^$/d' | wc -l | tr -d ' ')
  echo "  Applying $pending_count pending migration(s) from $DRIZZLE_DIR..."

  printf '%s\n' "$pending_migrations" | while IFS='|' read -r tag created_at hash; do
    [ -n "$tag" ] || continue
    migration_file="$DRIZZLE_DIR/$tag.sql"
    echo "    → $tag"

    {
      printf 'BEGIN;\n'
      cat "$migration_file"
      printf '\nINSERT INTO drizzle."__drizzle_migrations" (hash, created_at) VALUES (%s, %s);\n' "'$hash'" "$created_at"
      printf 'COMMIT;\n'
    } | docker exec -i -u postgres "$PG_CONTAINER" psql -v ON_ERROR_STOP=1 -U postgres -d main > /dev/null
  done
}

if docker_daemon_available; then
  # ── Fast path: if everything is already running, just check migrations ─
  # This makes multi-worktree setups fast while still keeping pg_hba/password
  # current for tailnet access.
  all_running=true
  for svc in postgres redis; do
    container=$(docker compose ps -q "$svc" 2>/dev/null)
    if [ -z "$container" ] || ! docker inspect "$container" --format='{{.State.Running}}' 2>/dev/null | grep -q true; then
      all_running=false
      break
    fi
  done

  if [ "$all_running" = true ]; then
    echo "All containers already running — checking network access and pending migrations..."
    PG_CONTAINER=$(docker compose ps -q postgres)
    prepare_docker_postgres "local-docker"
    echo ""
    echo "Development database is ready."
    echo "  Test user: test@boardsesh.com / test"
    exit 0
  fi

  # ── Cross-worktree fast path: postgres already running on port 5432 ─────
  # If another worktree already started the DB stack, reuse it instead of
  # starting duplicate containers (which would fail on port conflicts anyway).
  # Only reuse the container if it is actually the boardsesh dev DB image —
  # another project's postgres on port 5432 must not receive boardsesh migrations.
  PG_CONTAINER=$(docker ps --filter "publish=5432" --filter "status=running" -q 2>/dev/null | head -1)
  if [ -n "$PG_CONTAINER" ]; then
    PG_IMAGE=$(docker inspect "$PG_CONTAINER" --format='{{.Config.Image}}' 2>/dev/null)
    case "$PG_IMAGE" in
      *boardsesh-dev-db*) ;;
      *)
        echo "WARNING: A postgres container is running on port 5432 but it is not the boardsesh dev DB (expected image matching *boardsesh-dev-db*, got: $PG_IMAGE). Skipping cross-worktree fast path."
        PG_CONTAINER=""
        ;;
    esac
  fi
  if [ -n "$PG_CONTAINER" ]; then
    echo "Postgres already running on port 5432 (shared DB detected) — skipping container startup..."
    prepare_docker_postgres "shared-docker"
    echo ""
    echo "Development database is ready (shared from another worktree)."
    echo "  Test user: test@boardsesh.com / test"
    exit 0
  fi
fi

# ── Remote fast path: no local Docker DB is running, so try tailnet peers ─
# This lets smaller laptops use the pre-built DB stack from another machine
# without starting Docker locally.
set +e
"$REPO_ROOT/node_modules/.bin/tsx" "$REPO_ROOT/scripts/dev-db-discover.ts"
discover_status=$?
set -e
if [ "$discover_status" -eq 0 ]; then
  exit 0
fi
if [ "$discover_status" -ne 2 ]; then
  exit "$discover_status"
fi

ensure_docker_daemon

echo "Starting development database containers..."
docker compose up -d postgres redis

# Resolve container names dynamically (derived from directory name)
PG_CONTAINER=$(docker compose ps -q postgres)

echo "Waiting for postgres to be healthy..."
attempts=0
max_attempts=30
until docker exec "$PG_CONTAINER" pg_isready -U postgres -q 2>/dev/null; do
  attempts=$((attempts + 1))
  if [ "$attempts" -ge "$max_attempts" ]; then
    echo "ERROR: Postgres did not become ready within ${max_attempts}s"
    exit 1
  fi
  sleep 1
done
echo "Postgres is ready."

echo "Running database migrations..."
prepare_docker_postgres "local-docker"

echo ""
echo "Development database is ready."
echo "  Test user: test@boardsesh.com / test"
