/// <reference types="node" />

/**
 * Postcondition for a minified Android release: R8 must actually have run, and
 * it must actually have renamed things.
 *
 * Google Play's App optimisation report scored Boardsesh at Obfuscation 1%
 * because `minifyEnabled` had never been anything but false. The fix is a gradle
 * property written by packages/mobile/plugins/with-android-minify.js — but a
 * grep for that property passes in every scenario worth fearing:
 *
 *   - the property name is wrong for this template (SDK 56 spelled it
 *     `android.enableProguardInReleaseBuilds`), so we write a key nothing reads;
 *   - a future Expo template renames it again — android/ is regenerated by
 *     `expo prebuild --clean` every run, so nothing is pinned;
 *   - a keep rule goes too broad (`-keep class com.boardsesh.**`, or a new
 *     dependency's consumer rules), leaving minify on and the renamed fraction
 *     collapsing back toward zero.
 *
 * In all three the build is green, the APK ships readable, and Play stays at 1%.
 * So assert the ARTIFACT: R8's own mapping.txt, which only exists if R8 ran and
 * which says exactly what it renamed.
 *
 * Finding NO mapping is a failure, not a pass. "Nothing to check" is how a guard
 * like this goes vacuous when a build layout moves.
 *
 * Usage:
 *   vp run check:mobile-android-obfuscation -- --mapping <mapping.txt> \
 *     [--min-renamed-fraction 0.40] [--aab <file|dir>] [--summary]
 *
 * The caller names the file it just built rather than this script guessing a
 * default that could quietly drift onto an absent path and then "pass".
 */

import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { appendFileSync, existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = resolve(fileURLToPath(import.meta.url), '../..');

/**
 * Where AGP puts the R8 mapping inside an AAB. Play reads this slot on upload,
 * which is what makes Play-side deobfuscation free.
 */
export const AAB_MAPPING_ENTRY = 'BUNDLE-METADATA/com.android.tools.build.obfuscation/proguard.map';

/**
 * Names that must survive R8 with their original spelling, and the reason. Each
 * is reached by a string or a native symbol, so a rename is a runtime failure no
 * compiler can see. These are the cheapest possible proof that the keep rules in
 * with-android-minify.js actually reached R8 — a broken injection shows up here
 * before it shows up on a device.
 */
export const NAME_INVARIANTS: { className: string; why: string }[] = [
  {
    className: 'expo.modules.ExpoModulesPackageList',
    why: 'reached only via Class.forName; the three call sites swallow the failure, so a rename boots the app with ZERO Expo modules instead of crashing',
  },
  {
    className: 'com.boardsesh.boardrenderer.BoardRendererBridge',
    why: 'libboard_renderer_jni.so exports Java_com_boardsesh_boardrenderer_BoardRendererBridge_nativeRender; a rename is an UnsatisfiedLinkError on the first board render',
  },
  {
    className: 'com.swmansion.rnscreens.ScreenStackFragment',
    why: '@sentry/react-native compares this name as a string; a rename silently stops time-to-initial-display instrumentation',
  },
];

/** A mapping.txt class line: `<original> -> <obfuscated>:` at column 0. */
const CLASS_LINE = /^([\w$.[\]]+) -> ([\w$.[\]]+):$/;

export interface PackageStat {
  prefix: string;
  total: number;
  renamed: number;
}

export interface MappingStats {
  total: number;
  renamed: number;
  fraction: number;
  /** Original -> obfuscated, for the invariant lookups. */
  renames: Map<string, string>;
  /** Kept-heaviest packages first — names the culprit when the fraction drops. */
  byPackage: PackageStat[];
}

/**
 * Parses R8's mapping.txt. Members are indented and comments start with `#`, so
 * only column-0 lines are class entries.
 */
export function parseMapping(contents: string): MappingStats {
  const renames = new Map<string, string>();
  const packages = new Map<string, PackageStat>();
  let total = 0;
  let renamed = 0;

  for (const line of contents.split('\n')) {
    if (line.length === 0 || line.startsWith('#') || line.startsWith(' ') || line.startsWith('\t')) {
      continue;
    }
    const match = CLASS_LINE.exec(line.trimEnd());
    if (match === null) continue;

    const [, original, obfuscated] = match;
    if (original === undefined || obfuscated === undefined) continue;

    total += 1;
    renames.set(original, obfuscated);

    const wasRenamed = original !== obfuscated;
    if (wasRenamed) renamed += 1;

    // Two segments is the useful granularity: `com.boardsesh`, `expo.modules`,
    // `com.facebook` — enough to name the owner of a regression without
    // exploding into every leaf package.
    const prefix = original.split('.').slice(0, 2).join('.');
    const stat = packages.get(prefix) ?? { prefix, total: 0, renamed: 0 };
    stat.total += 1;
    if (wasRenamed) stat.renamed += 1;
    packages.set(prefix, stat);
  }

  const keptCount = (stat: PackageStat) => stat.total - stat.renamed;
  const byPackage = [...packages.values()].sort((a, b) => keptCount(b) - keptCount(a));

  return { total, renamed, fraction: total === 0 ? 0 : renamed / total, renames, byPackage };
}

export interface ObfuscationVerdict {
  ok: boolean;
  message: string;
}

export interface VerifyOptions {
  minFraction: number;
  /** A mapping this small is truncated or empty; it cannot pass at 100%. */
  minClasses: number;
}

export function verifyObfuscation(stats: MappingStats, { minFraction, minClasses }: VerifyOptions): ObfuscationVerdict {
  if (stats.total < minClasses) {
    return {
      ok: false,
      message:
        `R8's mapping lists only ${stats.total} classes (expected at least ${minClasses}). ` +
        'That is a truncated or near-empty mapping, which would pass a percentage check at 100% ' +
        'while proving nothing. Check that the mapping path names the release build you just ran.',
    };
  }

  // Absent is a failure too, not a pass: mapping.txt lists only classes that
  // SURVIVED, so a missing entry means R8 shrank the class away entirely — for
  // ExpoModulesPackageList that is the same catastrophic, silent outcome as a
  // rename. Treating `undefined` as fine is exactly the vacuous pass this script
  // exists to close.
  const broken = NAME_INVARIANTS.map(({ className, why }) => {
    const obfuscated = stats.renames.get(className);
    if (obfuscated === undefined) return { className, why, became: 'absent from the mapping (shrunk away)' };
    if (obfuscated !== className) return { className, why, became: `renamed to ${obfuscated}` };
    return null;
  }).filter((entry) => entry !== null);

  if (broken.length > 0) {
    const detail = broken.map(({ className, why, became }) => `  - ${className}: ${became}\n      ${why}`).join('\n');
    return {
      ok: false,
      message:
        `${broken.length} name(s) that must survive verbatim did not. The keep rules in ` +
        `packages/mobile/plugins/with-android-minify.js did not reach R8:\n${detail}`,
    };
  }

  const percent = (stats.fraction * 100).toFixed(1);
  if (stats.fraction < minFraction) {
    const worst = stats.byPackage
      .slice(0, 5)
      .map((stat) => `  - ${stat.prefix}: ${stat.total - stat.renamed} of ${stat.total} classes kept`)
      .join('\n');
    return {
      ok: false,
      message:
        `Only ${percent}% of classes were renamed (floor ${(minFraction * 100).toFixed(0)}%). ` +
        `A keep rule is too broad — every -keep lowers the number Google Play measures. ` +
        `Packages keeping the most classes:\n${worst}`,
    };
  }

  return {
    ok: true,
    message: `R8 renamed ${stats.renamed} of ${stats.total} classes (${percent}%); all ${NAME_INVARIANTS.length} name invariants intact.`,
  };
}

/** Resolves an AAB path from a file or a directory containing exactly one. */
export function resolveAabPath(target: string): string {
  if (!existsSync(target)) {
    throw new Error(`No such AAB path: ${target}`);
  }
  if (!statSync(target).isDirectory()) return target;

  const bundles = readdirSync(target).filter((name) => name.endsWith('.aab'));
  if (bundles.length !== 1) {
    throw new Error(
      `Expected exactly one .aab in ${target}, found ${bundles.length}: ${bundles.join(', ') || '(none)'}`,
    );
  }
  return join(target, bundles[0]!);
}

/**
 * The one invariant worth more than either check alone: the mapping Play
 * receives inside the AAB is byte-identical to the mapping we upload to Sentry.
 * A mismatch means the two systems deobfuscate against different builds.
 */
export function verifyAabMapping(aabPath: string, mappingContents: string): ObfuscationVerdict {
  let embedded: Buffer;
  try {
    embedded = execFileSync('unzip', ['-p', aabPath, AAB_MAPPING_ENTRY], {
      maxBuffer: 256 * 1024 * 1024,
      stdio: ['ignore', 'pipe', 'ignore'],
    });
  } catch {
    return {
      ok: false,
      message:
        `The AAB carries no ${AAB_MAPPING_ENTRY}, so Google Play cannot deobfuscate this release. ` +
        'AGP embeds that entry automatically when minification is on — its absence means the bundle ' +
        'was built unminified.',
    };
  }

  const digestOf = (buffer: Buffer | string) => createHash('sha256').update(buffer).digest('hex');
  const embeddedDigest = digestOf(embedded);
  const localDigest = digestOf(mappingContents);
  if (embeddedDigest !== localDigest) {
    return {
      ok: false,
      message:
        'The mapping embedded in the AAB differs from mapping.txt, so the mapping Google Play uses is ' +
        `not the one uploaded to Sentry (aab ${embeddedDigest.slice(0, 12)} vs local ${localDigest.slice(0, 12)}). ` +
        'The AAB and the APK were built from different R8 runs.',
    };
  }

  return { ok: true, message: `The AAB carries the same mapping (sha256 ${localDigest.slice(0, 12)}).` };
}

function readFlag(argv: string[], flag: string): string | undefined {
  const index = argv.indexOf(flag);
  return index === -1 ? undefined : argv[index + 1];
}

export function main(argv: string[] = process.argv.slice(2)): number {
  const args = argv.filter((arg) => arg !== '--');
  const mappingArg = readFlag(args, '--mapping');
  if (mappingArg === undefined) {
    console.error(
      '[mobile-android-obfuscation] Usage: --mapping <mapping.txt> [--min-renamed-fraction 0.40] [--aab <file|dir>] [--summary]',
    );
    return 1;
  }

  const minFraction = Number(readFlag(args, '--min-renamed-fraction') ?? '0.40');
  if (!Number.isFinite(minFraction) || minFraction <= 0 || minFraction > 1) {
    console.error(`[mobile-android-obfuscation] --min-renamed-fraction must be in (0, 1], got ${minFraction}.`);
    return 1;
  }

  const mappingPath = resolve(REPO_ROOT, mappingArg);
  if (!existsSync(mappingPath)) {
    console.error(
      `[mobile-android-obfuscation] R8 produced no mapping file at ${mappingPath}. Either minification did ` +
        'not run (the gradle property this build writes is not the one the generated build.gradle reads), ' +
        "or the output layout moved. Either way Google Play's App optimisation report stays at 1%.",
    );
    return 1;
  }

  const mappingContents = readFileSync(mappingPath, 'utf-8');
  const stats = parseMapping(mappingContents);
  const verdict = verifyObfuscation(stats, { minFraction, minClasses: 2000 });

  console[verdict.ok ? 'log' : 'error'](`[mobile-android-obfuscation] ${verdict.message}`);

  let aabVerdict: ObfuscationVerdict | undefined;
  const aabArg = readFlag(args, '--aab');
  if (aabArg !== undefined) {
    try {
      aabVerdict = verifyAabMapping(resolveAabPath(resolve(REPO_ROOT, aabArg)), mappingContents);
    } catch (error) {
      aabVerdict = { ok: false, message: error instanceof Error ? error.message : String(error) };
    }
    console[aabVerdict.ok ? 'log' : 'error'](`[mobile-android-obfuscation] ${aabVerdict.message}`);
  }

  if (args.includes('--summary') && process.env.GITHUB_STEP_SUMMARY) {
    const percent = (stats.fraction * 100).toFixed(1);
    const lines = [
      '### Android obfuscation (R8)',
      '',
      `- Classes renamed: **${stats.renamed} / ${stats.total} (${percent}%)** — floor ${(minFraction * 100).toFixed(0)}%`,
      `- Name invariants: ${verdict.ok ? 'intact' : 'BROKEN'}`,
      ...(aabVerdict ? [`- AAB mapping: ${aabVerdict.message}`] : []),
      '',
      'Top packages by kept classes:',
      ...stats.byPackage
        .slice(0, 5)
        .map((stat) => `- \`${stat.prefix}\`: ${stat.total - stat.renamed} of ${stat.total} kept`),
    ];
    appendFileSync(process.env.GITHUB_STEP_SUMMARY, `${lines.join('\n')}\n`);
  }

  return verdict.ok && (aabVerdict?.ok ?? true) ? 0 : 1;
}

if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  process.exit(main());
}
