#!/usr/bin/env bash
set -euo pipefail

# Regenerate the bundled-asset manifest for the React Native app's native
# board renderer. We do NOT copy or duplicate files — Metro watches the
# monorepo root (packages/mobile/metro.config.js sets watchFolders to
# monorepoRoot), so the manifest can require() directly out of
# packages/web/public/images/. Metro auto-bundles every require()'d
# asset into the IPA/APK, regardless of assetBundlePatterns.
#
# When the web image set changes, re-run this script and commit the
# updated manifest. The manifest is small (~300 lines); the underlying
# assets live in exactly one place (the web package).
#
# Preference order per (board, relative path) tuple:
#   1. .webp variant (3-4x smaller than .png, decoded natively on both
#      iOS UIImage and Android BitmapFactory)
#   2. .png fallback (only when no .webp exists)
#
# Both full-quality and `thumbs/` variants are bundled. Small/decorative
# surfaces (list thumbnails, blurred playlist backdrops) resolve the
# 416px-wide `thumbs/<name>.webp` so expo-image never resamples a ~1080px
# source on the main thread (the iOS app-hang fix); the full-size play
# view uses the full-quality file. A `thumbs/` file becomes its own
# manifest key (e.g. `kilter/product_sizes_layouts_sets/thumbs/54.webp`),
# which background-image-cache.ts looks up for the thumb variant (falling
# back to the full-quality key when a board has no thumb). The RN app does
# no server fetches, so every image it can render must come from this
# manifest.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
WEB_IMAGES="$ROOT_DIR/packages/web/public/images"
MANIFEST_FILE="$ROOT_DIR/packages/mobile/src/lib/board-backgrounds-manifest.ts"

if [ ! -d "$WEB_IMAGES" ]; then
  echo "ERROR: $WEB_IMAGES not found" >&2
  exit 1
fi

# require() path from MANIFEST_FILE (packages/mobile/src/lib/) up to the
# monorepo root, then into packages/web/public/images.
#   packages/mobile/src/lib/  -> ../../../ -> packages/  -> web/public/images
REQUIRE_PREFIX="../../../web/public/images"

# Pick the preferred variant (.webp first, .png fallback) per logical key
# (board + path without extension). Output one line per chosen file:
#   <logical_key>\t<actual_relative_path>
declare -A chosen
while IFS= read -r -d '' src_path; do
  rel_to_images="${src_path#$WEB_IMAGES/}"
  # Thumbs ARE included now: a thumbs/ path is its own logical key, so it
  # is bundled alongside the full-quality file (see header comment).
  logical_key="${rel_to_images%.*}"
  ext="${rel_to_images##*.}"
  current="${chosen[$logical_key]:-}"
  if [ -z "$current" ]; then
    chosen[$logical_key]="$rel_to_images"
  else
    current_ext="${current##*.}"
    # Prefer webp over png
    if [ "$ext" = "webp" ] && [ "$current_ext" = "png" ]; then
      chosen[$logical_key]="$rel_to_images"
    fi
  fi
done < <(find "$WEB_IMAGES" -type f \( -name '*.webp' -o -name '*.png' \) -print0)

# Sort the chosen relative paths for stable diffs.
chosen_paths=()
for logical_key in "${!chosen[@]}"; do
  chosen_paths+=("${chosen[$logical_key]}")
done
IFS=$'\n' sorted_paths=($(printf '%s\n' "${chosen_paths[@]}" | sort))
unset IFS

count="${#sorted_paths[@]}"

{
  echo "// AUTO-GENERATED by scripts/sync-mobile-board-backgrounds.sh"
  echo "// Do not edit by hand — re-run the sync script instead."
  echo "//"
  echo "// Keys are URL suffixes relative to https://www.boardsesh.com/images/,"
  echo "// e.g. 'kilter/product_sizes_layouts_sets/36-1.webp'. Values are Metro"
  echo "// module IDs produced by require() — Metro auto-bundles every"
  echo "// require()'d asset into the IPA/APK. The require paths reach across"
  echo "// the monorepo into packages/web/public/images, which Metro watches"
  echo "// via packages/mobile/metro.config.js (watchFolders = monorepoRoot)."
  echo "// This keeps the canonical asset set in one place (the web package)."
  echo ""
  echo "/* eslint-disable @typescript-eslint/no-require-imports */"
  echo "export const BOARD_BACKGROUND_ASSETS: Record<string, number> = {"
  for rel in "${sorted_paths[@]}"; do
    echo "  '$rel': require('$REQUIRE_PREFIX/$rel'),"
  done
  echo "};"
} > "$MANIFEST_FILE"

echo "==> Wrote $count entries to $MANIFEST_FILE"
echo "    (No files copied — Metro reads from packages/web/public/images directly.)"
