// @vitest-environment node

import { afterEach, beforeEach, describe, expect, it, vi } from 'vite-plus/test';
import { NextRequest } from 'next/server';

vi.mock('server-only', () => ({}));

const trackServerMock = vi.hoisted(() => vi.fn());
const aliasServerMock = vi.hoisted(() => vi.fn());
const flushServerAnalyticsMock = vi.hoisted(() => vi.fn(async () => {}));
const resolveAttributionMock = vi.hoisted(() =>
  vi.fn(async () => ({ distinctId: 'anon-uuid-123', isAuthenticated: false })),
);

vi.mock('@/app/lib/analytics.server', () => ({
  trackServer: trackServerMock,
  aliasServer: aliasServerMock,
  flushServerAnalytics: flushServerAnalyticsMock,
  resolveRequestAttribution: resolveAttributionMock,
}));

const dbState = vi.hoisted(() => ({
  existingUserRows: [] as Array<{ id: string }>,
  insertError: null as unknown,
}));

vi.mock('@/app/lib/db/db', () => ({
  getDb: () => ({
    select: () => ({
      from: () => ({
        where: () => ({
          limit: async () => dbState.existingUserRows,
        }),
      }),
    }),
    transaction: async (fn: (tx: unknown) => Promise<void>) => {
      if (dbState.insertError) throw dbState.insertError;
      const tx = {
        insert: () => ({ values: async () => undefined }),
      };
      await fn(tx);
    },
  }),
}));

vi.mock('@/app/lib/db/schema', () => ({
  users: {},
  userCredentials: {},
  userProfiles: {},
  verificationTokens: {},
}));

vi.mock('bcryptjs', () => ({
  hash: vi.fn(async () => 'hashed'),
}));

const sendVerificationEmailMock = vi.hoisted(() => vi.fn(async () => {}));
vi.mock('@/app/lib/email/email-service', () => ({
  sendVerificationEmail: sendVerificationEmailMock,
}));

const checkRateLimitMock = vi.hoisted(() => vi.fn(() => ({ limited: false, retryAfterSeconds: 0 })));
vi.mock('@/app/lib/auth/rate-limiter', () => ({
  checkRateLimit: checkRateLimitMock,
  getClientIp: () => '127.0.0.1',
}));

const ORIGINAL_ENV = process.env.EMAIL_VERIFICATION_ENABLED;

function jsonRequest(body: object): NextRequest {
  return new NextRequest(new URL('http://localhost:3000/api/auth/register'), {
    method: 'POST',
    body: JSON.stringify(body),
    headers: { 'content-type': 'application/json' },
  });
}

async function importGet() {
  vi.resetModules();
  const mod = await import('../route');
  return mod.POST;
}

describe('api/auth/register analytics', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    dbState.existingUserRows = [];
    dbState.insertError = null;
    checkRateLimitMock.mockReturnValue({ limited: false, retryAfterSeconds: 0 });
    sendVerificationEmailMock.mockResolvedValue(undefined);
    delete process.env.EMAIL_VERIFICATION_ENABLED;
  });

  afterEach(() => {
    if (ORIGINAL_ENV === undefined) delete process.env.EMAIL_VERIFICATION_ENABLED;
    else process.env.EMAIL_VERIFICATION_ENABLED = ORIGINAL_ENV;
  });

  it('emits Sign Up Attempted with the anonymous distinct id on entry', async () => {
    const POST = await importGet();
    await POST(jsonRequest({ email: 'a@b.com', password: 'password123' }));

    expect(trackServerMock).toHaveBeenCalledWith('Sign Up Attempted', {
      distinctId: 'anon-uuid-123',
      properties: { provider: 'email' },
    });
  });

  it('aliases anon → user in the canonical direction (userId surviving)', async () => {
    const POST = await importGet();
    const response = await POST(jsonRequest({ email: 'new@user.com', password: 'password123' }));
    const body = await response.json();

    expect(response.status).toBe(201);
    expect(body.requiresVerification).toBe(false);

    expect(aliasServerMock).toHaveBeenCalledTimes(1);
    const [distinctIdArg, aliasArg] = aliasServerMock.mock.calls[0];
    // userId is generated by crypto.randomUUID() inside the route handler;
    // assert by shape rather than value, and assert direction explicitly.
    expect(distinctIdArg).toMatch(/^[0-9a-f-]{36}$/);
    expect(aliasArg).toBe('anon-uuid-123');
    // Sign Up Succeeded fires on the new (canonical) user id.
    expect(trackServerMock).toHaveBeenCalledWith(
      'Sign Up Succeeded',
      expect.objectContaining({ distinctId: distinctIdArg }),
    );
    expect(flushServerAnalyticsMock).toHaveBeenCalled();
  });

  it('emits Sign Up Failed with errorKind=email_exists when the user already exists', async () => {
    dbState.existingUserRows = [{ id: 'existing' }];
    const POST = await importGet();
    const response = await POST(jsonRequest({ email: 'existing@user.com', password: 'password123' }));

    expect(response.status).toBe(409);
    expect(trackServerMock).toHaveBeenCalledWith('Sign Up Failed', {
      distinctId: 'anon-uuid-123',
      properties: { provider: 'email', errorKind: 'email_exists' },
    });
    expect(aliasServerMock).not.toHaveBeenCalled();
  });

  it('emits Sign Up Failed with errorKind=rate_limited when throttled', async () => {
    checkRateLimitMock.mockReturnValue({ limited: true, retryAfterSeconds: 30 });
    const POST = await importGet();
    const response = await POST(jsonRequest({ email: 'x@y.com', password: 'password123' }));

    expect(response.status).toBe(429);
    expect(trackServerMock).toHaveBeenCalledWith('Sign Up Failed', {
      distinctId: 'anon-uuid-123',
      properties: { provider: 'email', errorKind: 'rate_limited' },
    });
  });
});
