'use client';

import React from 'react';
import Box from '@mui/material/Box';
import MuiLink from '@mui/material/Link';
import { useTranslation } from 'react-i18next';
import LocaleLink from '@/app/components/i18n/locale-link';
import StartClimbingButton from '@/app/components/start-climbing-button';
import { brandCtaSx } from '@/app/components/ui/brand-cta';
import { PageShell, PageSection, Prose, ProseList } from '@/app/components/ui/page-shell';

const DISCORD_INVITE_URL = 'https://discord.gg/YXA8GsXfQK';
const GITHUB_ISSUES_URL = 'https://github.com/boardsesh/boardsesh/issues';
// Anchor for /help#climb-counts, linked from docs/kilter-sync.md.
const CLIMB_COUNTS_SECTION_ID = 'climb-counts';

const CTA_SX = brandCtaSx();

/**
 * The front-door help page.
 *
 * It used to document nine interactive features — the heatmap, party mode, the
 * queue bar, the playlist generator, hold search — with screenshots generated by
 * an e2e run that drove those very surfaces. Climbing moved to the app, so both
 * the features and the screenshot pipeline are gone. What is left is an honest
 * split: what this site does, what the app does, and where to ask.
 */
export default function HelpContent() {
  const { t } = useTranslation('marketing');

  return (
    <PageShell title={t('help.hero.title')} lead={t('help.hero.subtitle')}>
      <PageSection title={t('help.web.title')} lead={t('help.web.intro')}>
        <ProseList>
          <li>{t('help.web.item1')}</li>
          <li>{t('help.web.item2')}</li>
          <li>{t('help.web.item3')}</li>
          <li>{t('help.web.item4')}</li>
        </ProseList>
        <Prose>
          <MuiLink component={LocaleLink} href="/playlists">
            {t('help.web.playlistsLink')}
          </MuiLink>
          {' · '}
          <MuiLink component={LocaleLink} href="/about">
            {t('help.web.aboutLink')}
          </MuiLink>
        </Prose>
      </PageSection>

      <PageSection title={t('help.app.title')} lead={t('help.app.intro')}>
        <ProseList>
          <li>{t('help.app.item1')}</li>
          <li>{t('help.app.item2')}</li>
          <li>{t('help.app.item3')}</li>
          <li>{t('help.app.item4')}</li>
        </ProseList>
        <Box sx={{ mt: 2 }}>
          <StartClimbingButton
            label={t('help.app.cta')}
            ariaLabel={t('help.app.ctaAriaLabel')}
            size="medium"
            sx={CTA_SX}
          />
        </Box>
      </PageSection>

      <PageSection title={t('help.aurora.title')} lead={t('help.aurora.intro')}>
        <ProseList>
          <li>{t('help.aurora.item1')}</li>
          <li>{t('help.aurora.item2')}</li>
        </ProseList>
        <Prose>
          <MuiLink component={LocaleLink} href="/aurora-migration">
            {t('help.aurora.link')}
          </MuiLink>
        </Prose>
      </PageSection>

      <PageSection id={CLIMB_COUNTS_SECTION_ID} title={t('help.climbCounts.title')} lead={t('help.climbCounts.intro')}>
        <ProseList>
          <li>{t('help.climbCounts.item1')}</li>
          <li>{t('help.climbCounts.item2')}</li>
          <li>{t('help.climbCounts.item3')}</li>
        </ProseList>
      </PageSection>

      <PageSection title={t('help.ask.title')} lead={t('help.ask.intro')}>
        <ProseList>
          <li>
            <MuiLink href={DISCORD_INVITE_URL} target="_blank" rel="noopener noreferrer">
              {t('help.ask.discord')}
            </MuiLink>
          </li>
          <li>
            <MuiLink href={GITHUB_ISSUES_URL} target="_blank" rel="noopener noreferrer">
              {t('help.ask.github')}
            </MuiLink>
          </li>
          <li>
            <MuiLink component={LocaleLink} href="/docs">
              {t('help.ask.docs')}
            </MuiLink>
          </li>
        </ProseList>
      </PageSection>
    </PageShell>
  );
}
