/**
 * Export `hold_outline_overrides` rows to the committed JSON files the board-art
 * generator merges into its shards.
 *
 * The overrides table is where a human's correction to a traced hold silhouette
 * lives (see `docs/board-art-geometry.md`). A row in a database nobody can read
 * at build time is not something `scripts/generate-board-art-geometry.ts` can
 * merge, so this script is the one-way bridge: DB rows out, one JSON file per
 * `(board, layout, size)` under
 * `packages/shared/board-art-geometry/overrides/`, committed alongside the
 * regenerated shards.
 *
 * Committed rather than fetched because the generator has to be reproducible
 * from the repo alone: CI's drift gate reruns it with no database, and a
 * contributor regenerating shards on a laptop must produce the same bytes as the
 * run that shipped them.
 *
 * Output is deterministic — placements sorted numerically, ring values written
 * verbatim (the backend already stores them rounded to 4 decimals, so there is
 * no float round-trip here), fixed key order, trailing newline — so a re-export
 * with unchanged rows produces no diff.
 *
 * Usage:
 *   vp run db:export-outline-overrides
 *
 * There is no `--check` here and there does not need to be one. The enforcement
 * is `vp run check:board-art-geometry`: an override file that changed without
 * the shards being regenerated fails that gate, which is the failure that
 * actually matters — a correction nobody can see.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { asc, eq } from 'drizzle-orm';
import { SUPPORTED_BOARDS } from '@boardsesh/shared-schema';
import { createScriptDb, describeDatabaseHost, getScriptDatabaseUrl } from './db-connection.js';
import { holdOutlineOverrides } from '../src/schema/app/hold-outline-overrides.js';
import { userProfiles } from '../src/schema/auth/credentials.js';
import { users } from '../src/schema/auth/users.js';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(scriptDir, '../../..');
const OVERRIDES_DIR = path.join(REPO_ROOT, 'packages/shared/board-art-geometry/overrides');

/**
 * `board_name` is a free-text column, so a row's value reaches this script
 * unvalidated and then becomes a path segment. `../../..` in that column would
 * write outside the overrides tree.
 */
const KNOWN_BOARD_NAMES: ReadonlySet<string> = new Set(SUPPORTED_BOARDS);

const GENERATED_COMMENT =
  'Hand-drawn hold outline corrections. Generated by vp run db:export-outline-overrides — do not edit by hand.';

/** One placement's provenance, for humans reading the PR. Never read by the generator. */
type OverrideMeta = {
  author?: string;
  updatedAt: string;
  note?: string;
  kinds: string[];
};

type OverrideFile = {
  $comment: string;
  outlines?: Record<string, number[]>;
  ledInner?: Record<string, number[]>;
  meta?: Record<string, OverrideMeta>;
};

type OverrideRow = {
  boardName: string;
  layoutId: number;
  sizeId: number;
  placementId: number;
  kind: string;
  outline: number[];
  note: string | null;
  updatedAt: Date;
  authorDisplayName: string | null;
  authorName: string | null;
  authorEmail: string | null;
};

/** `<board>/<layoutId>-<sizeId>` — the shard's own merge key. */
function shardKeyFor(row: Pick<OverrideRow, 'boardName' | 'layoutId' | 'sizeId'>): string {
  return `${row.boardName}/${row.layoutId}-${row.sizeId}`;
}

/**
 * Who to credit. `displayName ?? name ?? email`, the same precedence the
 * overrides resolver uses for `author` — an override is reviewed by a human
 * reading a diff, and "corrected by marco" answers the question a bare user id
 * does not.
 *
 * Whatever wins is then cut at the `@`. These files are public and `name` is
 * free text a user typed: plenty of accounts carry an email address in it, and
 * publishing one because it arrived through the name column rather than the
 * email column would be the same leak by another route.
 */
function authorLabel(row: OverrideRow): string | undefined {
  const candidate = [row.authorDisplayName, row.authorName, row.authorEmail]
    .map((value) => value?.trim() ?? '')
    .find((value) => value !== '');
  if (candidate === undefined) return undefined;
  const local = candidate.split('@')[0].trim();
  return local === '' ? undefined : local;
}

/**
 * The file for one config's rows.
 *
 * Empty maps are omitted rather than written as `{}`: a config with only LED
 * annotations should not carry an `outlines: {}` that reads as "every silhouette
 * was reviewed and left alone".
 */
function buildOverrideFile(rows: OverrideRow[]): OverrideFile {
  const byPlacement = [...rows].sort((left, right) =>
    left.placementId === right.placementId ? left.kind.localeCompare(right.kind) : left.placementId - right.placementId,
  );

  const outlines: Record<string, number[]> = {};
  const ledInner: Record<string, number[]> = {};
  const kindsByPlacement = new Map<number, string[]>();
  // The newest touch on a placement is the one worth showing, whichever kind it
  // landed on: a reviewer wants "last changed by X on Y", not one entry per ring.
  const newestByPlacement = new Map<number, OverrideRow>();

  for (const row of byPlacement) {
    const placementKey = String(row.placementId);
    if (row.kind === 'led_inner') ledInner[placementKey] = row.outline;
    else outlines[placementKey] = row.outline;

    kindsByPlacement.set(row.placementId, [...(kindsByPlacement.get(row.placementId) ?? []), row.kind].sort());
    const newest = newestByPlacement.get(row.placementId);
    if (newest === undefined || row.updatedAt > newest.updatedAt) newestByPlacement.set(row.placementId, row);
  }

  const meta: Record<string, OverrideMeta> = {};
  for (const [placementId, kinds] of [...kindsByPlacement.entries()].sort(([left], [right]) => left - right)) {
    const newest = newestByPlacement.get(placementId) as OverrideRow;
    const author = authorLabel(newest);
    meta[String(placementId)] = {
      ...(author === undefined ? {} : { author }),
      updatedAt: newest.updatedAt.toISOString(),
      ...(newest.note === null ? {} : { note: newest.note }),
      kinds,
    };
  }

  return {
    $comment: GENERATED_COMMENT,
    ...(Object.keys(outlines).length > 0 ? { outlines } : {}),
    ...(Object.keys(ledInner).length > 0 ? { ledInner } : {}),
    ...(Object.keys(meta).length > 0 ? { meta } : {}),
  };
}

/** Stable, `vp fmt`-compatible serialisation: 2-space JSON with a trailing newline. */
function renderOverrideFile(file: OverrideFile): string {
  return `${JSON.stringify(file, null, 2)}\n`;
}

/** Every `<board>/<layout>-<size>.json` currently committed, as shard keys. */
function existingOverrideKeys(overridesDir: string): string[] {
  if (!fs.existsSync(overridesDir)) return [];
  const keys: string[] = [];
  for (const boardEntry of fs.readdirSync(overridesDir, { withFileTypes: true })) {
    if (!boardEntry.isDirectory()) continue;
    for (const fileEntry of fs.readdirSync(path.join(overridesDir, boardEntry.name), { withFileTypes: true })) {
      if (!fileEntry.isFile() || !fileEntry.name.endsWith('.json')) continue;
      keys.push(`${boardEntry.name}/${fileEntry.name.slice(0, -'.json'.length)}`);
    }
  }
  return keys.sort();
}

async function fetchRows(): Promise<OverrideRow[]> {
  const databaseUrl = getScriptDatabaseUrl();
  console.info(`[outline-overrides] reading from ${describeDatabaseHost(databaseUrl)}`);
  const { db, close } = createScriptDb(databaseUrl);
  try {
    const selected = await db
      .select({
        boardName: holdOutlineOverrides.boardName,
        layoutId: holdOutlineOverrides.layoutId,
        sizeId: holdOutlineOverrides.sizeId,
        placementId: holdOutlineOverrides.placementId,
        kind: holdOutlineOverrides.kind,
        outline: holdOutlineOverrides.outline,
        note: holdOutlineOverrides.note,
        updatedAt: holdOutlineOverrides.updatedAt,
        authorDisplayName: userProfiles.displayName,
        authorName: users.name,
        authorEmail: users.email,
      })
      .from(holdOutlineOverrides)
      .leftJoin(users, eq(users.id, holdOutlineOverrides.authorId))
      .leftJoin(userProfiles, eq(userProfiles.userId, holdOutlineOverrides.authorId))
      .orderBy(
        asc(holdOutlineOverrides.boardName),
        asc(holdOutlineOverrides.layoutId),
        asc(holdOutlineOverrides.sizeId),
        asc(holdOutlineOverrides.placementId),
        asc(holdOutlineOverrides.kind),
      );
    return selected.map((row) => ({ ...row, outline: row.outline as number[] }));
  } finally {
    await close();
  }
}

async function main(): Promise<number> {
  const rows = await fetchRows();

  // `board_name` is free text in the table and becomes a directory name below,
  // so it is checked against the catalogue before it is ever path-joined. Fail
  // the whole run rather than skipping the row: a board this script does not
  // recognise means either a typo nobody will otherwise notice or a new board
  // whose overrides would silently stop being exported.
  const unknownBoards = [...new Set(rows.map((row) => row.boardName))].filter(
    (boardName) => !KNOWN_BOARD_NAMES.has(boardName),
  );
  if (unknownBoards.length > 0) {
    console.error(
      `❌ hold_outline_overrides has row(s) for unknown board(s): ${unknownBoards.map((name) => `"${name}"`).join(', ')}.` +
        `\n   Known boards: ${[...KNOWN_BOARD_NAMES].join(', ')}`,
    );
    return 1;
  }

  const byKey = new Map<string, OverrideRow[]>();
  for (const row of rows) {
    const key = shardKeyFor(row);
    const bucket = byKey.get(key);
    if (bucket) bucket.push(row);
    else byKey.set(key, [row]);
  }

  // Written unconditionally rather than compared first. `vp fmt` runs over these
  // files right after this script, so the bytes on disk are prettier's and the
  // bytes here are `JSON.stringify`'s — a text comparison between the two would
  // report every file stale forever. The serialisation is deterministic, so a
  // rewrite with unchanged rows converges to the same file and git sees nothing.
  for (const [key, configRows] of [...byKey.entries()].sort(([left], [right]) => (left < right ? -1 : 1))) {
    const absolutePath = path.join(OVERRIDES_DIR, `${key}.json`);
    fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
    fs.writeFileSync(absolutePath, renderOverrideFile(buildOverrideFile(configRows)));
    console.info(`[outline-overrides] wrote ${key}.json (${configRows.length} row(s))`);
  }

  // A config whose last override was deleted has to lose its file, or the
  // generator keeps merging a correction the database no longer holds.
  let removed = 0;
  const expected = new Set(byKey.keys());
  for (const key of existingOverrideKeys(OVERRIDES_DIR).filter((existing) => !expected.has(existing))) {
    fs.rmSync(path.join(OVERRIDES_DIR, `${key}.json`));
    removed += 1;
    console.info(`[outline-overrides] removed ${key}.json — no rows left`);
  }

  // An emptied board directory would otherwise linger and be walked by the next
  // `existingOverrideKeys` pass. Git does not track it either way.
  if (fs.existsSync(OVERRIDES_DIR)) {
    for (const boardEntry of fs.readdirSync(OVERRIDES_DIR, { withFileTypes: true })) {
      if (!boardEntry.isDirectory()) continue;
      const boardDir = path.join(OVERRIDES_DIR, boardEntry.name);
      if (fs.readdirSync(boardDir).length === 0) fs.rmSync(boardDir, { recursive: true });
    }
  }

  console.info(
    `✓ ${rows.length} override row(s) across ${byKey.size} config(s)` +
      (removed > 0 ? `, ${removed} file(s) removed` : ''),
  );
  console.info('  Next: vp run generate:board-art-geometry, then commit the overrides and the shards together.');
  return 0;
}

main()
  .then((code) => process.exit(code))
  .catch((error: unknown) => {
    console.error('[outline-overrides] failed:', error);
    process.exit(1);
  });
