/**
 * Markdown section walker for pull-request bodies.
 *
 * One parser, three readers: the changelog generator (`## Release Notes`), the
 * PR gate (`## Test plan` + `## Risk`), and the backend that serves a PR's test
 * plan to testers in the mobile app. Keeping the walker here means a body that
 * passes CI parses identically everywhere else.
 *
 * Pure: no I/O, no globals.
 */

// Any markdown ATX heading — bounds a section.
export const ANY_HEADING = /^#{1,6}\s+/;
// HTML comments (the authoring guide in the PR template) — stripped before parse.
export const HTML_COMMENT = /<!--[\s\S]*?-->/g;
// Leading list markers (`- `, `* `, `+ `, `1. `) so a bulleted line reads cleanly.
export const LIST_MARKER = /^(?:[-*+]|\d+\.)\s+/;
// A fenced-code-block delimiter. Tracked so a `#` line *inside* a fence doesn't
// get mistaken for the section's end heading.
export const CODE_FENCE = /^\s*```/;
// Also ends a section (besides the next heading): a markdown horizontal rule, or
// an auto-generated PR footer — the "🤖 Generated with…" line, or the italicised
// "_Generated by [Claude Code](…)_" variant claude.ai/code sessions append. Stops
// a footer that sits right after the section — with no heading to bound it — from
// leaking in. The italic delimiter is mandatory so real prose starting with
// "Generated by…" is never mistaken for the footer (a `* ` bullet has a space
// after the marker, so bulleted prose can't match either).
export const SECTION_BREAK = /^\s*(?:(?:-{3,}|\*{3,}|_{3,})\s*$|🤖|[_*]generated (?:by|with)\s)/i;
// A git trailer line — the `*-by:` family (Co-Authored-By, Signed-off-by,
// Reviewed-by, …) plus Change-Id. Agent-authored PR bodies carry these after the
// last section with nothing to bound them (see PR #3367, where a Co-Authored-By
// trailer shipped as a What's New card title). Never copy a human should read, so
// drop the line wherever it appears. Deliberately NOT a generic `word:` match —
// prose like "Faster search: results in half the time" must survive.
export const GIT_TRAILER = /^(?:[a-z][a-z-]*-by|change-id):\s/i;
// A line that is nothing but a URL (e.g. a bare claude.ai/code session link, see
// PR #3180). A URL inside a sentence is kept; a link-only line is never copy.
export const BARE_URL_LINE = /^https?:\/\/\S+$/i;

/** Strips HTML comments (the PR template's authoring guides) from a body. */
export function stripHtmlComments(body: string): string {
  return body.replace(HTML_COMMENT, '');
}

/**
 * Index of the first line matching `heading` that is not inside a fenced code
 * block — a `## Test plan` quoted as an example in a Summary fence must not be
 * mistaken for the real section (the gate would validate the example, or stop at
 * its next heading and never see the tester-facing plan).
 */
function findHeadingOutsideFences(lines: readonly string[], heading: RegExp): number {
  let insideFence = false;
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    if (CODE_FENCE.test(line)) {
      insideFence = !insideFence;
      continue;
    }
    if (!insideFence && heading.test(line)) return index;
  }
  return -1;
}

/**
 * Lines of `body` that sit outside fenced code blocks (fence delimiters
 * dropped too), comments stripped. For readers that scan a whole body rather
 * than one section.
 */
export function linesOutsideFences(body: string): string[] {
  const kept: string[] = [];
  let insideFence = false;
  for (const line of stripHtmlComments(body).split(/\r?\n/)) {
    if (CODE_FENCE.test(line)) {
      insideFence = !insideFence;
      continue;
    }
    if (!insideFence) kept.push(line);
  }
  return kept;
}

/**
 * Returns the raw lines of the section under the first heading matching
 * `heading`: everything up to the next markdown heading, horizontal rule, or
 * bot footer (or EOF), ignoring boundaries inside fenced code blocks. Fence
 * delimiter lines are kept so a caller can still tell code from prose. HTML
 * comments are stripped first so a commented-out heading inside the template's
 * guide can't be mistaken for a boundary. Returns null when the heading is absent.
 */
export function extractSection(body: string | null | undefined, heading: RegExp): string[] | null {
  if (!body) return null;

  const lines = stripHtmlComments(body).split(/\r?\n/);
  const headingIndex = findHeadingOutsideFences(lines, heading);
  if (headingIndex === -1) return null;

  const sectionLines: string[] = [];
  let insideFence = false;
  for (let index = headingIndex + 1; index < lines.length; index += 1) {
    const line = lines[index];
    if (CODE_FENCE.test(line)) {
      insideFence = !insideFence;
      sectionLines.push(line);
      continue;
    }
    if (!insideFence && (ANY_HEADING.test(line) || SECTION_BREAK.test(line))) break;
    sectionLines.push(line);
  }
  return sectionLines;
}

/**
 * True for a line that is never content: a git trailer or a link-only line.
 * Shared by every section reader so junk is dropped the same way everywhere.
 */
export function isJunkLine(line: string): boolean {
  return GIT_TRAILER.test(line) || BARE_URL_LINE.test(line);
}
