/// <reference types="node" />
/**
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY ⚠️
 *
 * This file is auto-generated by running:
 *   bun run --filter=@boardsesh/board-constants generate
 *
 * Lazy per-board hole-placement loader. Each board's holds live in their own
 * `.cjs` shard under `generated/hole-placements/`; the loader requires only the
 * board that is asked for, so Hermes (Android, no JIT) never has to evaluate every
 * board's holds at once. See `generate-board-constants.ts` for why the shards are
 * `.cjs` rather than `.ts`.
 *
 * The `/// <reference types="node" />` above types the global `require` and
 * `process` this loader uses, in every consuming package — board-constants itself
 * sets no `types` field, and shared packages that import it (play-view,
 * climb-filters, …) compile without Node's lib. It is a type-only directive, so
 * it changes nothing at runtime in Metro/webpack.
 *
 * This file is structural (no board data), so it carries no generation timestamp
 * — regenerating with unchanged board data produces a byte-identical file and no
 * spurious diff.
 */

import type { BoardName } from '@boardsesh/shared-schema';
import type { HoldTuple } from './types';

type BoardHolePlacements = Record<string, HoldTuple[]>;

// Frozen so the shared singleton returned for boards without a shard (moonboard,
// unknown names) can't be mutated by one caller and corrupt every other.
const EMPTY_BOARD: BoardHolePlacements = Object.freeze({});

// Metro (mobile), webpack (web), and the vitest test runtime inject a global,
// synchronous `require`; the literal `require('./generated/hole-placements/…cjs')`
// calls below let those bundlers statically resolve each shard and lazily
// evaluate only the requested board.
//
// Bare Node ESM (the tsx-run generator scripts, the backend, aurora-sync, the db
// test runner) has no global `require`. There we build one with `createRequire`,
// reached through `process.getBuiltinModule` so this module never statically
// imports a Node builtin (which Metro could not resolve) and never touches
// `import.meta` (which Metro's CommonJS transform does not support). That Node
// `createRequire` is anchored to this module's URL, so the same relative shard
// paths resolve in both branches.
const hasGlobalRequire = typeof require === 'function';

let cachedNodeRequire: ((path: string) => unknown) | null = null;
function nodeRequire(): (path: string) => unknown {
  if (cachedNodeRequire) return cachedNodeRequire;
  const getBuiltinModule = (process as unknown as { getBuiltinModule?: (id: string) => unknown }).getBuiltinModule;
  if (typeof getBuiltinModule !== 'function') {
    // process.getBuiltinModule landed in Node 22.3. The repo pins
    // `engines.node: 22.x`, so this only fires if board-constants is consumed by
    // a bare Node ESM runtime older than that — surface it clearly rather than
    // failing on an undefined call.
    throw new Error(
      'No global require, and process.getBuiltinModule is unavailable. ' +
        'Loading hole-placement shards from bare Node ESM needs Node 22.3+ (the repo pins engines.node 22.x).',
    );
  }
  const moduleBuiltin = getBuiltinModule('node:module') as {
    createRequire: (path: string | URL) => (path: string) => unknown;
  };
  // Anchor createRequire to *this* module's URL so the relative shard paths
  // resolve next to the loader, regardless of the caller's cwd or how the
  // workspace is linked. `import.meta.url` is only read here, in the Node-only
  // branch — Metro/webpack/vitest take the global-`require` branch above and
  // never evaluate this function.
  cachedNodeRequire = moduleBuiltin.createRequire(import.meta.url);
  return cachedNodeRequire;
}

/* eslint-disable @typescript-eslint/no-require-imports */
const HOLE_PLACEMENT_SHARD_LOADERS: Record<string, () => BoardHolePlacements> = {
  kilter: () =>
    hasGlobalRequire
      ? (require('./generated/hole-placements/kilter.cjs') as BoardHolePlacements)
      : (nodeRequire()('./generated/hole-placements/kilter.cjs') as BoardHolePlacements),
  tension: () =>
    hasGlobalRequire
      ? (require('./generated/hole-placements/tension.cjs') as BoardHolePlacements)
      : (nodeRequire()('./generated/hole-placements/tension.cjs') as BoardHolePlacements),
  decoy: () =>
    hasGlobalRequire
      ? (require('./generated/hole-placements/decoy.cjs') as BoardHolePlacements)
      : (nodeRequire()('./generated/hole-placements/decoy.cjs') as BoardHolePlacements),
  touchstone: () =>
    hasGlobalRequire
      ? (require('./generated/hole-placements/touchstone.cjs') as BoardHolePlacements)
      : (nodeRequire()('./generated/hole-placements/touchstone.cjs') as BoardHolePlacements),
  grasshopper: () =>
    hasGlobalRequire
      ? (require('./generated/hole-placements/grasshopper.cjs') as BoardHolePlacements)
      : (nodeRequire()('./generated/hole-placements/grasshopper.cjs') as BoardHolePlacements),
  soill: () =>
    hasGlobalRequire
      ? (require('./generated/hole-placements/soill.cjs') as BoardHolePlacements)
      : (nodeRequire()('./generated/hole-placements/soill.cjs') as BoardHolePlacements),
};
/* eslint-enable @typescript-eslint/no-require-imports */

const shardCache = new Map<string, BoardHolePlacements>();

/**
 * Return the hole placements for a single board, loading (and caching) just that
 * board's shard. Boards without a shard (e.g. `moonboard`, whose holds come from
 * handwritten helpers, not the Aurora generator) resolve to an empty record.
 */
export function getBoardHolePlacements(boardName: BoardName): BoardHolePlacements {
  const cached = shardCache.get(boardName);
  if (cached) return cached;

  const loader = HOLE_PLACEMENT_SHARD_LOADERS[boardName];
  const placements = loader ? loader() : EMPTY_BOARD;
  shardCache.set(boardName, placements);
  return placements;
}

// All board names that have (or could have) hole placements, including the
// non-Aurora `moonboard` so the proxy enumerates the same keys the old eager
// record did.
const ALL_BOARD_NAMES: BoardName[] = [
  ...(['kilter', 'tension', 'decoy', 'touchstone', 'grasshopper', 'soill'] as const),
  'moonboard',
];

/**
 * Backwards-compatible all-boards view. A Proxy keeps the old
 * `HOLE_PLACEMENTS[board][key]` and `Object.entries(HOLE_PLACEMENTS)` shapes
 * working for Node-side consumers (backend export, aurora-sync, the iOS Swift
 * generator) while still loading each board's shard lazily on first access — the
 * mobile hot path (`getBoardHolePlacements`) never forces the other boards.
 */
export const HOLE_PLACEMENTS: Record<BoardName, BoardHolePlacements> = new Proxy(
  {} as Record<BoardName, BoardHolePlacements>,
  {
    get(_target, property: string | symbol) {
      if (typeof property !== 'string' || !ALL_BOARD_NAMES.includes(property as BoardName)) {
        return undefined;
      }
      return getBoardHolePlacements(property as BoardName);
    },
    ownKeys() {
      return ALL_BOARD_NAMES;
    },
    has(_target, property: string | symbol) {
      return typeof property === 'string' && ALL_BOARD_NAMES.includes(property as BoardName);
    },
    getOwnPropertyDescriptor(_target, property: string | symbol) {
      // Guard like the get/has traps so an unknown key reports `undefined` rather
      // than a phantom descriptor — otherwise the three traps disagree and
      // descriptor-walking consumers (structuredClone, serializers) misbehave.
      if (typeof property !== 'string' || !ALL_BOARD_NAMES.includes(property as BoardName)) {
        return undefined;
      }
      // The target has no such own property and is extensible, so the descriptor
      // must be `configurable: true` to satisfy the Proxy invariant. Expose the
      // board's placements as the value so descriptor-walkers see real data.
      return {
        enumerable: true,
        configurable: true,
        writable: false,
        value: getBoardHolePlacements(property as BoardName),
      };
    },
  },
);
